agg_dict = {"dfhwbgds": {'wbgds_len': 'last', 'wbgds_id': 'last', 'wbgds_vers': 'last',
                         'wbg_urimap_reference_count': 'sum', 'wbg_urimap_match_disabled': 'sum',
                         'wbg_urimap_no_match_count': 'sum', 'wbg_urimap_match_count': 'sum',
                         'wbg_urimap_match_redirect': 'sum', 'wbg_urimap_match_analyzer': 'sum',
                         'wbg_urimap_static_content': 'last', 'wbg_urimap_dynamic_content': 'last',
                         'wbg_urimap_pipeline_reqs': 'sum', 'wbg_urimap_scheme_http': 'sum',
                         'wbg_urimap_scheme_https': 'sum', 'wbg_host_disabled_count': 'sum',
                         'wbg_urimap_atomserv_reqs': 'sum', 'wbg_urimap_jvmserver_reqs': 'sum',
                         'wbg_urimap_entrypoint_ref': 'sum', 'wbg_urimap_direct_attach': 'sum',
                         'wbg_urimap_scheme_jms': 'sum', 'wbg_urimap_scheme_iiop': 'sum'},
            "dfhisrds": {'isrds_len': 'last', 'isrds_id': 'last', 'isrds_vers': 'last', 'isr_applid': 'last',
                         'isr_network_id': 'last', 'isr_host_name': 'last', 'isr_port_number': 'last',
                         'isr_ssl_support': 'last', 'isr_userauth': 'last', 'isr_linkauth': 'last',
                         'isr_mirrorlife': 'last', 'isr_tcpip_service': 'last', 'isr_fs_ts_requests': 'sum',
                         'isr_fs_ts_bytes_sent': 'sum', 'isr_fs_ts_bytes_received': 'sum',
                         'isr_ipconn_gmt_create_time': 'last', 'isr_ipconn_create_time': 'last',
                         'isr_ipconn_gmt_delete_time': 'last', 'isr_ipconn_delete_time': 'last',
                         'isr_send_sessions': 'sum', 'isr_current_send_sessions': 'last',
                         'isr_peak_send_sessions': 'max', 'isr_receive_sessions': 'sum',
                         'isr_current_receive_sessions': 'last', 'isr_peak_receive_sessions': 'max',
                         'isr_tr_requests': 'sum', 'isr_tr_bytes_sent': 'sum', 'isr_tr_bytes_received': 'sum',
                         'isr_total_allocates': 'sum', 'isr_current_queued_allocates': 'last',
                         'isr_peak_queued_allocates': 'max', 'isr_allocates_failed_link': 'sum',
                         'isr_allocates_failed_other': 'sum', 'isr_fs_td_requests': 'sum',
                         'isr_fs_td_bytes_sent': 'sum',
                         'isr_fs_td_bytes_received': 'sum', 'isr_allocate_queue_limit': 'last',
                         'isr_qlimit_alloc_rejects': 'sum', 'isr_max_queue_time': 'max',
                         'isr_maxqtime_alloc_qpurges': 'sum', 'isr_maxqtime_allocs_purged': 'sum',
                         'isr_xisque_alloc_rejects': 'sum', 'isr_xisque_alloc_qpurges': 'sum',
                         'isr_xisque_allocs_purged': 'sum', 'isr_trans_attached': 'sum',
                         'isr_remote_term_starts': 'sum',
                         'isr_unsupported_requests': 'sum', 'isr_fs_pg_requests': 'sum', 'isr_fs_pg_bytes_sent': 'sum',
                         'isr_fs_pg_bytes_received': 'sum', 'isr_fs_ic_requests': 'sum', 'isr_fs_ic_bytes_sent': 'sum',
                         'isr_fs_ic_bytes_received': 'sum', 'isr_ipconn_ip_address': 'last',
                         'isr_ipconn_ip_family': 'last', 'isr_ipconn_define_source': 'last',
                         'isr_ipconn_change_time': 'last', 'isr_ipconn_change_userid': 'last',
                         'isr_ipconn_change_agent': 'last', 'isr_ipconn_install_agent': 'last',
                         'isr_ipconn_install_time': 'last', 'isr_ipconn_install_userid': 'last',
                         'isr_fs_fc_requests': 'sum', 'isr_fs_fc_bytes_sent': 'sum', 'isr_fs_fc_bytes_received': 'sum'},
            "dfhxmrds": {'xmrlen': 'last', 'xmrid': 'last', 'xmrdvers': 'last', 'xmrpn': 'last', 'xmrtcl': 'last',
                         'xmrrnam': 'last', 'xmrrsys': 'last', 'xmrprty': 'last', 'xmrdyn': 'last',
                         'xmr_otel_prop_status': 'last', 'xmrac': 'sum', 'xmrrc': 'sum', 'xmrdlc': 'sum',
                         'xmrdrc': 'sum', 'xmrrsc': 'sum', 'xmrsvc': 'sum', 'xmritov': 'last', 'xmriwtop': 'last',
                         'xmriactn': 'last', 'xmr_tran_entrypoint': 'last', 'xmr_otel_emit_status': 'last',
                         'xmriwait': 'sum', 'xmrfatxn': 'sum', 'xmrfait': 'sum', 'xmrfanw': 'sum', 'xmrfaop': 'sum',
                         'xmrfaot': 'sum', 'xmramism': 'sum', 'xmraendc': 'sum', 'xmr_purged_trncls_threshold': 'sum',
                         'xmr_otel_prop_count': 'sum', 'xmr_tran_define_source': 'last', 'xmr_tran_change_time': 'last',
                         'xmr_tran_change_userid': 'last', 'xmr_tran_change_agent': 'last',
                         'xmr_tran_install_agent': 'last', 'xmr_tran_install_time': 'last',
                         'xmr_tran_install_userid': 'last'},
            "dfhmlrds": {'mlrds_len': 'last', 'mlrds_id': 'last', 'mlrds_vers': 'last', 'mlr_msg_validation': 'last',
                         'mlr_xsdbind_file': 'last', 'mlr_xmlschema_file': 'last', 'mlr_xmltrnfm_use_count': 'sum',
                         'mlr_xmltrnfm_define_source': 'last', 'mlr_xmltrnfm_change_time': 'last',
                         'mlr_xmltrnfm_change_userid': 'last', 'mlr_xmltrnfm_change_agent': 'last',
                         'mlr_xmltrnfm_install_agent': 'last', 'mlr_xmltrnfm_install_time': 'last',
                         'mlr_xmltrnfm_install_userid': 'last'},
            "dfhmqrds": {'mqrlen': 'last', 'mqrid': 'last', 'mqrdvers': 'last', 'mqr_tranid': 'last',
                         'mqr_tasknum': 'last', 'mqr_monuserid': 'last', 'mqr_userid': 'last', 'mqr_monstatus': 'last',
                         'mqr_topen': 'sum', 'mqr_tclose': 'sum', 'mqr_tget': 'sum', 'mqr_tgetwait': 'sum',
                         'mqr_tput': 'sum', 'mqr_tput1': 'sum', 'mqr_tinq': 'sum', 'mqr_tinql': 'sum',
                         'mqr_tset': 'sum',
                         'mqr_tcommuow': 'sum', 'mqr_tbackuow': 'sum', 'mqr_tother': 'sum',
                         'mqr_start_time_gmt': 'last',
                         'mqr_start_time_local': 'last', 'mqr_stop_time_gmt': 'last', 'mqr_stop_time_local': 'last',
                         'mqr_mqmon_define_source': 'last', 'mqr_mqmon_change_time': 'last',
                         'mqr_mqmon_change_userid': 'last', 'mqr_mqmon_change_agent': 'last',
                         'mqr_mqmon_install_agent': 'last', 'mqr_mqmon_install_time': 'last',
                         'mqr_mqmon_install_userid': 'last'},
            "dfhmqgds": {'mqglen': 'last', 'mqgid': 'last', 'mqgdvers': 'last', 'mqg_mq_release': 'last',
                         'mqg_connection_status': 'last', 'mqg_resyncmember': 'last', 'mqg_initiation_queue': 'last',
                         'mqg_ttasks': 'last', 'mqg_tfutileatt': 'sum', 'mqg_tapi': 'sum', 'mqg_tapiok': 'sum',
                         'mqg_tcall': 'sum', 'mqg_tcallsynccomp': 'sum', 'mqg_tcallio': 'sum', 'mqg_twaitmsg': 'sum',
                         'mqg_tsubtasked': 'sum', 'mqg_topen': 'sum', 'mqg_tclose': 'sum', 'mqg_tget': 'sum',
                         'mqg_tgetwait': 'sum', 'mqg_tput': 'sum', 'mqg_tput1': 'sum', 'mqg_tinq': 'sum',
                         'mqg_tset': 'sum', 'mqg_indoubtuow': 'sum', 'mqg_unresolveduow': 'sum',
                         'mqg_resolvecomm': 'sum', 'mqg_resolveback': 'sum', 'mqg_tbackuow': 'sum',
                         'mqg_tcommuow': 'sum', 'mqg_ttaskend': 'sum', 'mqg_tspcomm': 'sum', 'mqg_t2pcomm': 'sum',
                         'mqg_tcb': 'sum', 'mqg_tconsume': 'sum', 'mqg_tctl': 'sum', 'mqg_tsub': 'sum',
                         'mqg_tsubrq': 'sum', 'mqg_tstat': 'sum', 'mqg_tcrtmh': 'sum', 'mqg_tdltmh': 'sum',
                         'mqg_tsetmp': 'sum', 'mqg_tinqmp': 'sum', 'mqg_tdltmp': 'sum', 'mqg_tmhbuf': 'sum',
                         'mqg_tbufmh': 'sum', 'mqg_mqconn_name': 'last', 'mqg_mqname': 'last',
                         'mqg_connect_time_gmt': 'last', 'mqg_connect_time_local': 'last',
                         'mqg_disconnect_time_gmt': 'last', 'mqg_disconnect_time_local': 'last',
                         'mqg_mqconn_define_source': 'last', 'mqg_mqconn_change_time': 'last',
                         'mqg_mqconn_change_userid': 'last', 'mqg_mqconn_change_agent': 'last',
                         'mqg_mqconn_install_agent': 'last', 'mqg_mqconn_install_time': 'last',
                         'mqg_mqconn_install_userid': 'last'},
            "dfhpgrds": {'pgrds_len': 'last', 'pgrds_id': 'last', 'pgrds_vers': 'last',
                         'pgr_jvmprogram_entrypoint': 'last', 'pgr_jvmprogram_usecount': 'sum',
                         'pgr_jvmprogram_exec_key': 'last', 'pgr_jvmprogram_jvmclass': 'last',
                         'pgr_jvmprogram_server': 'last'},
            "dfha16ds": {'a16len': 'last', 'a16id': 'last', 'a16dvers': 'last'},
            "dfhldbds": {'ldbds_len': 'last', 'ldbds_id': 'last', 'ldbds_vers': 'last',
                         'ldb_library_search_pos': 'last',
                         'ldb_library_ranking': 'last', 'ldb_library_critical': 'last',
                         'ldb_library_enable_status': 'last', 'ldb_library_prog_loads': 'sum',
                         'ldb_library_define_source': 'last', 'ldb_library_change_time': 'last',
                         'ldb_library_change_userid': 'last', 'ldb_library_change_agent': 'last',
                         'ldb_library_install_agent': 'last', 'ldb_library_install_time': 'last',
                         'ldb_library_install_userid': 'last', 'ldb_library_numdsnames': 'last'},
            "dsgtcbp": {'dsgmxtcb': 'max', 'dsgcnuat': 'last', 'dsgpnuat': 'max', 'dsgcnuus': 'last', 'dsgpnuus': 'max',
                        'dsgntcbl': 'sum', 'dsgtotwl': 'sum', 'dsgcurwt': 'last', 'dsgtotnw': 'sum', 'dsgcurnw': 'last',
                        'dsgpeanw': 'max', 'dsgmmwts': 'sum', 'dsgmmwtm': 'sum', 'dsgcmmws': 'last', 'dsgpmmws': 'max',
                        'dsgcmmwt': 'last', 'dsggtcbl': 'last', 'dsgltcbl': 'last'},
            "smsbody": {'smslocn': 'last', 'smsaccess': 'last', 'smsdsaindex': 'last', 'smsdsasz': 'last',
                        'smshwmdsasz': 'max', 'smscsize': 'last', 'smsgmreq': 'sum', 'smsfmreq': 'sum', 'smsasr': 'sum',
                        'smsdsr': 'sum', 'smscriss': 'sum', 'smsucss': 'sum', 'smscss': 'last', 'smshwmss': 'max',
                        'smspwws': 'sum', 'smscrel': 'sum', 'smssos': 'sum', 'smstsos': 'sum', 'smscsubp': 'last',
                        'smsfstg': 'sum', 'smshwmfstg': 'max', 'smslwmfstg': 'min', 'smslfa': 'max', 'smssv': 'sum',
                        'smsexts': 'last', 'smsextsa': 'sum', 'smsextsr': 'sum', 'smsdsalimit': 'last',
                        'smsedsalimit': 'last'},
            "dfha24ds": {'a24len': 'last', 'a24id': 'last', 'a24dvers': 'last', 'a24pool': 'last', 'a24appl': 'last',
                         'a24ndct': 'sum', 'a24alloc': 'sum', 'a24totwt': 'sum', 'a24wait': 'last', 'a24pkwt': 'max',
                         'a24tiout': 'sum'},
            "dfha23ds": {'a23len': 'last', 'a23id': 'last', 'a23dvers': 'last', 'a23targ': 'last', 'a23node': 'last',
                         'a23acq': 'sum', 'a23cnv': 'sum', 'a23usi': 'sum', 'a23chout': 'sum', 'a23chin': 'sum',
                         'a23rtout': 'sum', 'a23error': 'sum'},
            "dfhtqgds": {'tqglen': 'last', 'tqgid': 'last', 'tqgdvers': 'last', 'tqganbfa': 'last', 'tqgamxiu': 'max',
                         'tqgatnal': 'sum', 'tqgamxal': 'max', 'tqgatnwt': 'sum', 'tqgamxwt': 'max', 'tqgacisz': 'last',
                         'tqgancis': 'last', 'tqgamxci': 'max', 'tqganosp': 'sum', 'tqgactpt': 'sum', 'tqgactgt': 'sum',
                         'tqgactft': 'sum', 'tqgactio': 'sum', 'tqgsnsta': 'last', 'tqgstnal': 'sum', 'tqgsmxal': 'max',
                         'tqgstnwt': 'sum', 'tqgsmxwt': 'max', 'tqgacnal': 'last', 'tqgacnwt': 'last',
                         'tqgacniu': 'last', 'tqgscnal': 'last', 'tqgscnwt': 'last', 'tqgactci': 'last'},
            "dfhwbrds": {'wbrds_len': 'last', 'wbrds_id': 'last', 'wbrds_vers': 'last', 'wbr_urimap_usage': 'last',
                         'wbr_urimap_scheme': 'last', 'wbr_urimap_analyzer_use': 'last',
                         'wbr_urimap_redirect_type': 'last', 'wbr_urimap_authenticate': 'last',
                         'wbr_urimap_attls': 'last', 'wbr_urimap_entrypoint': 'last', 'wbr_urimap_hostname': 'last',
                         'wbr_urimap_port': 'last', 'wbr_urimap_path': 'last', 'wbr_urimap_templatename': 'last',
                         'wbr_urimap_hfsfile': 'last', 'wbr_urimap_location': 'last', 'wbr_urimap_trans_id': 'last',
                         'wbr_urimap_tcpipservice': 'last', 'wbr_urimap_converter': 'last',
                         'wbr_urimap_program_name': 'last', 'wbr_urimap_webservice': 'last',
                         'wbr_urimap_pipeline': 'last', 'wbr_urimap_atomservice': 'last',
                         'wbr_urimap_reference_count': 'sum', 'wbr_urimap_match_disabled': 'sum',
                         'wbr_urimap_match_redirect': 'sum', 'wbr_urimap_socketclose': 'last',
                         'wbr_urimap_sockpoolsize': 'last', 'wbr_urimap_sockpoolsize_peak': 'max',
                         'wbr_urimap_sockets_reclaimed': 'sum', 'wbr_urimap_sockets_timedout': 'sum',
                         'wbr_urimap_ip_address': 'last', 'wbr_urimap_ip_family': 'last',
                         'wbr_urimap_define_source': 'last', 'wbr_urimap_change_time': 'last',
                         'wbr_urimap_change_userid': 'last', 'wbr_urimap_change_agent': 'last',
                         'wbr_urimap_install_agent': 'last', 'wbr_urimap_install_time': 'last',
                         'wbr_urimap_install_userid': 'last'},
            "dfhcfs6d": {'s6len': 'last', 's6id': 'last', 's6dvers': 'last', 's6pref': 'last', 's6cnpref': 'last',
                         's6cnsysn': 'last', 's6size': 'last', 's6sizemx': 'max', 's6hdrs': 'max', 's6hdrsct': 'last',
                         's6hdrstd': 'last', 's6elemln': 'last', 's6elempw': 'last', 's6elempe': 'max',
                         's6elemrt': 'last', 's6entrrt': 'last', 's6entrct': 'last', 's6entrhi': 'max',
                         's6entrlo': 'min', 's6entrmx': 'max', 's6elemct': 'last', 's6elemhi': 'max', 's6elemlo': 'min',
                         's6elemmx': 'max', 's6usedct': 'last', 's6usedhi': 'max', 's6freect': 'last',
                         's6freehi': 'max',
                         's6indxct': 'last', 's6indxhi': 'max', 's6applct': 'last', 's6applhi': 'max',
                         's6uowlct': 'last', 's6uowlhi': 'max', 's6rdict': 'sum', 's6wrict': 'sum', 's6rwict': 'sum',
                         's6dlict': 'sum', 's6crlct': 'sum', 's6mdlct': 'sum', 's6dllct': 'sum', 's6rddct': 'sum',
                         's6wrdct': 'sum', 's6rwdct': 'sum', 's6dldct': 'sum', 's6inlct': 'sum', 's6rdmct': 'sum',
                         's6wrmct': 'sum', 's6rduct': 'sum', 's6wruct': 'sum', 's6rwuct': 'sum', 's6dluct': 'sum',
                         's6rdact': 'sum', 's6wract': 'sum', 's6rwact': 'sum', 's6dlact': 'sum', 's6rrlct': 'sum',
                         's6asyct': 'sum', 's6rsp1ct': 'sum', 's6rsp2ct': 'sum', 's6rsp3ct': 'sum', 's6rsp4ct': 'sum',
                         's6rsp5ct': 'sum', 's6rsp6ct': 'sum', 's6rsp7ct': 'sum', 's6rsp8ct': 'sum', 's6rsp9ct': 'sum'},
            "dfhcfs7d": {'s7len': 'last', 's7id': 'last', 's7dvers': 'last', 's7ocopen': 'sum', 's7occlos': 'sum',
                         's7ocset': 'sum', 's7ocdele': 'sum', 's7ocstat': 'sum', 's7rqpoin': 'sum', 's7rqhigh': 'sum',
                         's7rqread': 'sum', 's7rqrddl': 'sum', 's7rqunlk': 'sum', 's7rqload': 'sum', 's7rqwrit': 'sum',
                         's7rqrewr': 'sum', 's7rqdele': 'sum', 's7rqdelm': 'sum'},
            "dfha22ds": {'a22len': 'last', 'a22id': 'last', 'a22dvers': 'last', 'a22trgct': 'sum', 'a22ndct': 'sum',
                         'a22conct': 'sum', 'a22conpk': 'max', 'a22alloc': 'sum', 'a22pkall': 'max', 'a22wait': 'last',
                         'a22totwt': 'sum', 'a22pkwt': 'max', 'a22tiout': 'sum'},
            "ldgglobal": {'ldgllr': 'sum', 'ldgllt': 'sum', 'ldgpuses': 'sum', 'ldgwlr': 'sum', 'ldgwlrhw': 'max',
                          'ldghwmt': 'sum', 'ldgttw': 'sum', 'ldgdrebs': 'sum', 'ldgwtdlr': 'sum', 'ldgllrro': 'sum',
                          'ldglltro': 'sum', 'ldglwsou': 'sum', 'ldglsort': 'last', 'ldglbsou': 'sum'},
            "dfhpgeds": {'pgeds_len': 'last', 'pgeds_id': 'last', 'pgeds_vers': 'last',
                         'pge_program_platform_name': 'last', 'pge_program_application_name': 'last',
                         'pge_program_appl_major_ver': 'last', 'pge_program_appl_minor_ver': 'last',
                         'pge_program_appl_micro_ver': 'last', 'pge_program_name': 'last', 'pge_program_type': 'last',
                         'pge_program_exec_key': 'last', 'pge_program_data_loc': 'last',
                         'pge_program_execution_set': 'last', 'pge_program_lang_deduced': 'last',
                         'pge_program_language': 'last', 'pge_program_runtime_env': 'last',
                         'pge_program_concurrency': 'last', 'pge_program_api': 'last', 'pge_program_remote': 'last',
                         'pge_program_dynamic': 'last', 'pge_program_jvm': 'last', 'pge_program_entrypoint': 'last',
                         'pge_program_remote_name': 'last', 'pge_program_tran_id': 'last',
                         'pge_program_remote_sysid': 'last', 'pge_program_jvmserver': 'last',
                         'pge_program_define_source': 'last', 'pge_program_change_time': 'last',
                         'pge_program_change_userid': 'last', 'pge_program_change_agent': 'last',
                         'pge_program_install_agent': 'last', 'pge_program_install_time': 'last',
                         'pge_program_install_userid': 'last', 'pge_program_operation_name': 'last'},
            "dfhxmgds": {'xmglen': 'last', 'xmgid': 'last', 'xmgdvers': 'last', 'xmgnum': 'sum', 'xmgmxt': 'last',
                         'xmgcat': 'last', 'xmgcqt': 'last', 'xmgtamxt': 'sum', 'xmgpat': 'max', 'xmgpqt': 'max',
                         'xmgtat': 'sum', 'xmgtdt': 'sum', 'xmgtqtme': 'sum', 'xmgcqtme': 'last', 'xmgtnum': 'last',
                         'xmggtat': 'last', 'xmgltat': 'last', 'xmggsmxt': 'last', 'xmglsmxt': 'last',
                         'xmggamxt': 'last', 'xmglamxt': 'last', 'xmgatmxt': 'last', 'xmgotel': 'last'},
            "dfhsmtds": {'smtlen': 'last', 'smtid': 'last', 'smtdvers': 'last', 'smtntask': 'last'},
            "dfhldrds": {'ldrlen': 'last', 'ldrid': 'last', 'ldrdvers': 'last', 'ldrtu': 'sum', 'ldrfc': 'sum',
                         'ldrft': 'sum', 'ldrtn': 'sum', 'ldrpsize': 'last', 'ldrrpc': 'sum', 'ldrlocn': 'last',
                         'ldrlbnm': 'last', 'ldrlbdnm': 'last'},
            "dfhtqrds": {'tqrlen': 'last', 'tqrid': 'last', 'tqrdvers': 'last', 'tqrqtype': 'last', 'tqrwrite': 'sum',
                         'tqrread': 'sum', 'tqrdelet': 'sum', 'tqrtrigl': 'last', 'tqrrtype': 'last',
                         'tqrftype': 'last',
                         'tqrfname': 'last', 'tqrwait': 'last', 'tqrwaita': 'last', 'tqratran': 'last',
                         'tqrtrign': 'sum', 'tqrccius': 'last', 'tqrpcius': 'max', 'tqrcnitm': 'last',
                         'tqrrsys': 'last',
                         'tqrrqid': 'last', 'tqriqid': 'last', 'tqriotyp': 'last', 'tqrddnm': 'last',
                         'tqrdsnnm': 'last',
                         'tqrpdsmn': 'last', 'tqr_define_source': 'last', 'tqr_change_time': 'last',
                         'tqr_change_userid': 'last', 'tqr_change_agent': 'last', 'tqr_install_agent': 'last',
                         'tqr_install_time': 'last', 'tqr_install_userid': 'last', 'tqrpnitm': 'max'},
            "dfha17ds": {'a17len': 'last', 'a17id': 'last', 'a17dvers': 'last', 'a17floc': 'last', 'a17dt': 'last',
                         'a17dsrls': 'last', 'a17dsnam': 'last', 'a17dsrd': 'sum', 'a17dsgu': 'sum', 'a17dsbr': 'sum',
                         'a17dswra': 'sum', 'a17dswru': 'sum', 'a17dsdel': 'sum', 'a17dsxcp': 'sum', 'a17dsixp': 'sum',
                         'a17dstsw': 'sum', 'a17dshsw': 'max', 'a17dttyp': 'last', 'a17dtrds': 'sum', 'a17dtrnf': 'sum',
                         'a17dtavr': 'sum', 'a17dtads': 'sum', 'a17dtarj': 'sum', 'a17dtatf': 'sum', 'a17dtrws': 'sum',
                         'a17dtdls': 'sum', 'a17dtshi': 'max', 'a17dtsiz': 'last', 'a17dtalt': 'max', 'a17dtust': 'max',
                         'a17dtale': 'max', 'a17dtuse': 'max', 'a17dtali': 'max', 'a17dtusi': 'max', 'a17dtald': 'max',
                         'a17dtusd': 'max', 'a17dtrrs': 'sum', 'a17dsdnb': 'sum', 'a17dsinb': 'sum', 'a17pool': 'last',
                         'a17strno': 'sum', 'a17rname': 'last', 'a17rsys': 'last', 'a17dstyp': 'last',
                         'a17bdsnm': 'last', 'a17dsasc': 'sum', 'a17dsasw': 'sum', 'a17lopnt': 'last',
                         'a17lclst': 'last', 'a17gopnt': 'last', 'a17gclst': 'last', 'a17dsbru': 'sum',
                         'a17rlswt': 'sum', 'a17dtcon': 'sum', 'a17dtcfp': 'last', 'a17dtlds': 'sum', 'a17fcxcc': 'sum',
                         'a17_file_define_source': 'last', 'a17_file_change_time': 'last',
                         'a17_file_change_userid': 'last', 'a17_file_change_agent': 'last',
                         'a17_file_install_agent': 'last', 'a17_file_install_time': 'last',
                         'a17_file_install_userid': 'last'},
            "dfha09ds": {'a09len': 'last', 'a09id': 'last', 'a09dvers': 'last', 'a09srpid': 'last', 'a09dbn': 'last',
                         'a09ibn': 'last', 'a09tbw': 'sum', 'a09hbw': 'max'},
            "dfhdsrds": {'dsrds_len': 'last', 'dsrds_id': 'last', 'dsrds_vers': 'last', 'dsrds_tcb_name': 'last',
                         'dsrds_tcb_type': 'last', 'dsrds_tcb_cics_task': 'last', 'dsrds_tcb_mother': 'last',
                         'dsrds_tcb_sister': 'last', 'dsrds_tcb_daughter': 'last', 'dsrds_tcb_cputime': 'sum',
                         'dsrds_tcb_stg_below': 'max', 'dsrds_tcb_stg_above': 'max',
                         'dsrds_tcb_stg_below_inuse': 'last',
                         'dsrds_tcb_stg_above_inuse': 'last'},
            "dfhsdgds": {'sdglen': 'last', 'sdgid': 'last', 'sdgdvers': 'last', 'sys_dumps_taken': 'sum',
                         'sys_dumps_suppr': 'sum'},
            "dfhdstds": {'dstds_len': 'last', 'dstds_id': 'last', 'dstds_vers': 'last', 'dstds_cicstcb_count': 'last',
                         'dstds_cicstcb_cputime': 'last', 'dstds_cicstcb_stg_below': 'max',
                         'dstds_cicstcb_stg_above': 'max', 'dstds_noncicstcb_count': 'last',
                         'dstds_noncicstcb_cputime': 'last', 'dstds_noncicstcb_stg_below': 'max',
                         'dstds_noncicstcb_stg_above': 'max', 'dstds_cicstcb_stg_below_inuse': 'last',
                         'dstds_cicstcb_stg_above_inuse': 'last', 'dstds_noncicstcb_stg_below_inuse': 'last',
                         'dstds_noncicstcb_stg_above_inuse': 'last'}, "ldb_dsnames": {},
            "dfha06ds": {'a06len': 'last', 'a06id': 'last', 'a06dvers': 'last', 'a06tett': 'last', 'a06eamib': 'last',
                         'a06lenp': 'sum', 'a06teni': 'sum', 'a06teno': 'sum', 'a06teot': 'sum', 'a06csvc': 'sum',
                         'a06tete': 'sum', 'a06teoe': 'sum', 'a06tcnt': 'sum', 'a06scnt': 'sum', 'a06mcnt': 'max',
                         'a06lunam': 'last', 'a06prty': 'last', 'a06stg': 'max', 'a06sysid': 'last', 'a06ontm': 'last',
                         'a06offtm': 'last', 'a06gontm': 'last', 'a06goftm': 'last'},
            "dfhw2rds": {'w2rds_len': 'last', 'w2rds_id': 'last', 'w2rds_vers': 'last', 'w2r_atomserv_type': 'last',
                         'w2r_atomserv_binding_file': 'last', 'w2r_atomserv_config_file': 'last',
                         'w2r_atomserv_restype': 'last', 'w2r_atomserv_resname': 'last',
                         'w2r_atomserv_ref_count': 'sum',
                         'w2r_atomserv_ref_disabled': 'sum', 'w2r_atomserv_post_feed_cnt': 'sum',
                         'w2r_atomserv_get_feed_cnt': 'sum', 'w2r_atomserv_get_entry_cnt': 'sum',
                         'w2r_atomserv_put_entry_cnt': 'sum', 'w2r_atomserv_del_entry_cnt': 'sum',
                         'w2r_atomserv_define_source': 'last', 'w2r_atomserv_change_time': 'last',
                         'w2r_atomserv_change_userid': 'last', 'w2r_atomserv_change_agent': 'last',
                         'w2r_atomserv_install_agent': 'last', 'w2r_atomserv_install_time': 'last',
                         'w2r_atomserv_install_userid': 'last', 'w2r_atomserv_urimap': 'last',
                         'w2r_atomserv_xmltransform': 'last'},
            "nqgbody": {'nqgtnqsi': 'sum', 'nqgtnqsw': 'sum', 'nqgtnqwt': 'sum', 'nqgcnqsw': 'last', 'nqgcnqwt': 'last',
                        'nqggnqsw': 'sum', 'nqggnqwt': 'sum', 'nqgsnqsw': 'last', 'nqgsnqwt': 'last', 'nqgtnqsr': 'sum',
                        'nqgtnqrt': 'sum', 'nqgcnqsr': 'last', 'nqgcnqrt': 'last', 'nqgtirjb': 'sum', 'nqgtirjr': 'sum',
                        'nqgtwrjr': 'sum', 'nqgtwpop': 'sum', 'nqgtwpto': 'sum'},
            "smsglobal": {'smslen': 'last', 'smsid': 'last', 'smsdvers': 'last',
                          'smsgbllen': 'last', 'smsnpagp': 'last', 'smsstgprot': 'last', 'smsrentpgm': 'last',
                          'smstraniso': 'last', 'smsmemlimitsrc': 'last', 'smsusscur': 'last', 'smsusscum': 'sum',
                          'smsusshwm': 'max', 'smscsscur': 'last', 'smscsscum': 'sum', 'smscsshwm': 'max',
                          'smsdsalimit': 'last', 'smsedsalimit': 'last', 'smsdsatotal': 'last', 'smsedsatotal': 'last',
                          'smshwmdsatotal': 'max', 'smshwmedsatotal': 'max', 'smstimewaitmvs': 'sum',
                          'smsmvsstgreqwaits': 'sum', 'smsmemlimit': 'last', 'smsgetstorsize': 'max',
                          'smsasactive': 'last', 'smshwmasactive': 'max', 'smsgdsaactive': 'last',
                          'smshwmgdsaactive': 'max', 'smsgdsaalloc': 'last', 'smshwmgdsaalloc': 'max',
                          'smslvabytes': 'max', 'smslvhbytes': 'max', 'smslvgbytes': 'max', 'smslvnmemobj': 'max',
                          'smsfromguardfail': 'sum', 'smsfromguardfailsize': 'max', 'smslvshrbytes': 'max',
                          'smslvshrgbytes': 'max', 'smslvshrnmemobj': 'max', 'smshvauxslots': 'max',
                          'smshvgauxslots': 'max', 'smshvpagesinreal': 'max', 'smshvgpagesinreal': 'max',
                          'smslargememobj': 'max', 'smslargepagesinreal': 'max'},
            "dfhsdrds": {'sdrlen': 'last', 'sdrid': 'last', 'sdrdvers': 'last', 'sdrstkn': 'sum', 'sdrssupr': 'sum',
                         'sdrttkn': 'sum', 'sdrtsupr': 'sum'},
            "dfhpgdds": {'pgdds_len': 'last', 'pgdds_id': 'last', 'pgdds_vers': 'last', 'pgd_program_type': 'last',
                         'pgd_program_exec_key': 'last', 'pgd_program_data_loc': 'last',
                         'pgd_program_execution_set': 'last', 'pgd_program_lang_deduced': 'last',
                         'pgd_program_language': 'last', 'pgd_program_runtime_env': 'last',
                         'pgd_program_concurrency': 'last', 'pgd_program_api': 'last', 'pgd_program_remote': 'last',
                         'pgd_program_dynamic': 'last', 'pgd_program_jvm': 'last', 'pgd_program_entrypoint': 'last',
                         'pgd_program_remote_name': 'last', 'pgd_program_tran_id': 'last',
                         'pgd_program_remote_sysid': 'last', 'pgd_program_jvmserver': 'last',
                         'pgd_program_define_source': 'last', 'pgd_program_change_time': 'last',
                         'pgd_program_change_userid': 'last', 'pgd_program_change_agent': 'last',
                         'pgd_program_install_agent': 'last', 'pgd_program_install_time': 'last',
                         'pgd_program_install_userid': 'last'},
            "dfha14ds": {'a14len': 'last', 'a14id': 'last', 'a14dvers': 'last', 'a14esall': 'last', 'a14ebid': 'last',
                         'a14estam': 'max', 'a14e2hwm': 'max', 'a14ebhwm': 'max', 'a14es1': 'sum', 'a14es2': 'sum',
                         'a14esbid': 'sum', 'a14estas': 'sum', 'a14estaq': 'sum', 'a14estaf': 'sum', 'a14estao': 'sum',
                         'a14estfc': 'sum', 'a14estic': 'sum', 'a14esttd': 'sum', 'a14estts': 'sum', 'a14estdl': 'sum',
                         'a14esttc': 'sum', 'a14e1hwm': 'max', 'a14eqpct': 'sum', 'a14ealrj': 'sum', 'a14emxqt': 'last',
                         'a14ealim': 'last', 'a14ezqrj': 'sum', 'a14ezqpu': 'sum', 'a14ezqpc': 'sum', 'a14emqpc': 'sum',
                         'a14eall': 'last', 'a14gact': 'last', 'a14aict': 'last', 'a14gadt': 'last', 'a14aidt': 'last',
                         'a14eahwm': 'max', 'a14esid': 'last', 'a14accm': 'last', 'a14eflgs': 'last', 'a14esecn': 'sum',
                         'a14eprmn': 'sum', 'a14e1ry': 'last', 'a14e2ry': 'last', 'a14estpc': 'sum',
                         'a14estpc_channel': 'sum', 'a14estpc_channel_sent': 'sum', 'a14estpc_channel_rcvd': 'sum',
                         'a14esttc_channel': 'sum', 'a14esttc_channel_sent': 'sum', 'a14esttc_channel_rcvd': 'sum',
                         'a14estic_channel': 'sum', 'a14estic_channel_sent': 'sum', 'a14estic_channel_rcvd': 'sum',
                         'a14_define_source': 'last', 'a14_change_time': 'last', 'a14_change_userid': 'last',
                         'a14_change_agent': 'last', 'a14_install_agent': 'last', 'a14_install_time': 'last',
                         'a14_install_userid': 'last'},
            "dfha20ds": {'a20len': 'last', 'a20id': 'last', 'a20dvers': 'last', 'a20estam': 'max', 'a20e2hwm': 'max',
                         'a20ebhwm': 'max', 'a20e1hwm': 'max', 'a20es1': 'sum', 'a20es2': 'sum', 'a20esbid': 'sum',
                         'a20estas': 'sum', 'a20estaq': 'sum', 'a20estaf': 'sum', 'a20estao': 'sum', 'a20estag': 'sum',
                         'a20estap': 'sum', 'a20ebid': 'last', 'a20eqpct': 'sum', 'a20ezqpc': 'sum', 'a20elmax': 'max',
                         'a20emcon': 'max', 'a20emaxs': 'last', 'a20econw': 'last', 'a20econl': 'last',
                         'a20e1ry': 'last', 'a20e2ry': 'last'},
            "dfhmprds": {'mprlen': 'last', 'mprid': 'last', 'mprdvers': 'last', 'mpr_policy_name': 'last',
                         'mpr_rule_name': 'last', 'mpr_policy_usertag': 'last', 'mpr_bundle_name': 'last',
                         'mpr_bundle_dir': 'last', 'mpr_rule_type': 'last', 'mpr_rule_subtype': 'last',
                         'mpr_action_type': 'last', 'mpr_action_count': 'sum', 'mpr_action_time': 'last'},
            "a08bssds": {'a08bkbfn': 'last', 'a08bkhbn': 'last', 'a08bkbff': 'sum', 'a08bkfrd': 'sum',
                         'a08bkuiw': 'sum',
                         'a08bknuw': 'sum', 'a08bkcrs': 'sum', 'a08bkcws': 'sum', 'a08bkcrf': 'sum', 'a08bkcwf': 'sum'},
            "dfha08ds": {'a08len': 'last', 'a08id': 'last', 'a08dvers': 'last', 'a08flags': 'last', 'a08lbkcd': 'last',
                         'a08lbkdd': 'last', 'a08gbkcd': 'last', 'a08gbkdd': 'last', 'a08bkkyl': 'max',
                         'a08bkstn': 'max', 'a08bkhsw': 'max', 'a08bktsw': 'sum', 'a08bkhas': 'max',
                         'a08tobfn_data': 'last', 'a08tohbn_data': 'last', 'a08tobff_data': 'sum',
                         'a08tofrd_data': 'sum', 'a08touiw_data': 'sum', 'a08tonuw_data': 'sum', 'a08tocrs_data': 'sum',
                         'a08tocws_data': 'sum', 'a08tocrf_data': 'sum', 'a08tocwf_data': 'sum',
                         'a08tobfn_indx': 'last',
                         'a08tohbn_indx': 'last', 'a08tobff_indx': 'sum', 'a08tofrd_indx': 'sum',
                         'a08touiw_indx': 'sum',
                         'a08tonuw_indx': 'sum', 'a08tocrs_indx': 'sum', 'a08tocws_indx': 'sum', 'a08tocrf_indx': 'sum',
                         'a08tocwf_indx': 'sum'},
            "dfhpirds": {'pirds_len': 'last', 'pirds_id': 'last', 'pirds_vers': 'last', 'pir_pipeline_name': 'last',
                         'pir_pipeline_mode': 'last', 'pir_configuration_file': 'last', 'pir_shelf_directory': 'last',
                         'pir_wsdir_directory': 'last', 'pir_pipeline_use_count': 'sum', 'pir_json_java_parser': 'last',
                         'pir_pipeline_define_source': 'last', 'pir_pipeline_change_time': 'last',
                         'pir_pipeline_change_userid': 'last', 'pir_pipeline_change_agent': 'last',
                         'pir_pipeline_install_agent': 'last', 'pir_pipeline_install_time': 'last',
                         'pir_pipeline_install_userid': 'last', 'pir_pipeline_msgformat': 'last'},
            "a16stats": {'a16tsize': 'last'},
            "dfhtdgds": {'tdglen': 'last', 'tdgid': 'last', 'tdgdvers': 'last', 'trans_dump_taken': 'sum',
                         'trans_dump_supp': 'sum'}, "ldy_dsnames": {'ldy_dsname': 'last'},
            "dfhepgds": {'epgds_len': 'last', 'epgds_id': 'last', 'epgds_vers': 'last', 'epg_put_events': 'sum',
                         'epg_commit_forward_events': 'sum', 'epg_commit_backward_events': 'sum',
                         'epg_current_evc_queue': 'last', 'epg_peak_evc_queue': 'max',
                         'epg_current_trans_queue': 'last',
                         'epg_peak_trans_queue': 'max', 'epg_async_normal_events': 'sum',
                         'epg_async_priority_events': 'sum', 'epg_trans_events': 'sum',
                         'epg_trans_events_discarded': 'sum', 'epg_sync_events': 'sum', 'epg_sync_events_failed': 'sum',
                         'epg_dispatchers_attached': 'sum', 'epg_current_dispatchers': 'last',
                         'epg_peak_dispatchers': 'max', 'epg_custom_adapter_events': 'sum',
                         'epg_wmq_adapter_events': 'sum', 'epg_trans_adapter_events': 'sum',
                         'epg_tsqueue_adapter_events': 'sum', 'epg_http_adapter_events': 'sum',
                         'epg_tdqueue_adapter_events': 'sum', 'epg_dispatch_failure_config': 'sum',
                         'epg_dispatch_failure_other': 'sum', 'epg_adapter_failure_config': 'sum',
                         'epg_adapter_failure_other': 'sum', 'epg_events_adapter_unavail': 'sum'},
            "dfheprds": {'eprds_len': 'last', 'eprds_id': 'last', 'eprds_vers': 'last', 'epr_adapter_type': 'last',
                         'epr_emission_mode': 'last', 'epr_put_events': 'sum', 'epr_ada_define_source': 'last',
                         'epr_ada_change_time': 'last', 'epr_ada_change_userid': 'last', 'epr_ada_change_agent': 'last',
                         'epr_ada_install_agent': 'last', 'epr_ada_install_time': 'last',
                         'epr_ada_install_userid': 'last'},
            "dfhasgds": {'asgds_len': 'last', 'asgds_id': 'last', 'asgds_vers': 'last', 'asg_run_count': 'sum',
                         'asg_fetch_count': 'sum', 'asg_free_count': 'sum', 'asg_run_delay_count': 'sum',
                         'asg_parents_delayed_cur': 'sum', 'asg_parents_delayed_peak': 'max', 'asg_children_cur': 'sum',
                         'asg_children_peak': 'max'},
            "dfhdhdds": {'dhdds_len': 'last', 'dhdds_id': 'last', 'dhdds_vers': 'last', 'dhd_template_type': 'last',
                         'dhd_append_crlf': 'last', 'dhd_template_contents': 'last', 'dhd_template_name': 'last',
                         'dhd_template_exit_program': 'last', 'dhd_template_file_name': 'last',
                         'dhd_template_program_name': 'last', 'dhd_template_pds_member': 'last',
                         'dhd_template_pds_ddname': 'last', 'dhd_template_pds_dsname': 'last',
                         'dhd_template_tdqueue_name': 'last', 'dhd_template_tsqueue_name': 'last',
                         'dhd_template_hfsfile_name': 'last', 'dhd_template_cache_size': 'last',
                         'dhd_template_use_count': 'sum', 'dhd_template_newcopies': 'sum',
                         'dhd_template_read_count': 'sum', 'dhd_template_cache_used': 'sum',
                         'dhd_template_cache_deleted': 'sum', 'dhd_template_define_source': 'last',
                         'dhd_template_change_time': 'last', 'dhd_template_change_userid': 'last',
                         'dhd_template_change_agent': 'last', 'dhd_template_install_agent': 'last',
                         'dhd_template_install_time': 'last', 'dhd_template_install_userid': 'last'},
            "dfha03ds": {'a03len': 'last', 'a03id': 'last', 'a03dvers': 'last', 'a03rplxt': 'sum', 'a03rplx': 'max',
                         'a03vtsos': 'sum', 'a03doc': 'sum', 'a03lunum': 'last', 'a03luhwm': 'max', 'a03psic': 'sum',
                         'a03psnc': 'sum', 'a03psoc': 'sum', 'a03psuc': 'sum', 'a03psec': 'sum', 'a03pstyp': 'last',
                         'a03psdin': 'last', 'a03bmvl': 'last', 'a03bmig': 'sum', 'a03bmlg': 'sum', 'a03bmab': 'sum'},
            "dfhsjsds": {'sjsds_len': 'last', 'sjsds_id': 'last', 'sjsds_vers': 'last',
                         'sjs_jvmserver_jvmprofile': 'last', 'sjs_jvmserver_le_runopts': 'last',
                         'sjs_jvmserver_use_count': 'sum', 'sjs_jvmserver_state': 'last',
                         'sjs_jvmserver_thread_limit': 'last', 'sjs_jvmserver_thread_current': 'last',
                         'sjs_jvmserver_thread_hwm': 'max', 'sjs_jvmserver_thread_waits': 'sum',
                         'sjs_jvmserver_thread_wait_time': 'sum', 'sjs_jvmserver_thread_wait_cur': 'last',
                         'sjs_jvmserver_thread_wait_hwm': 'max', 'sjs_jvmserver_thread_wlp_actv': 'max',
                         'sjs_jvmserver_define_source': 'last', 'sjs_jvmserver_change_time': 'last',
                         'sjs_jvmserver_change_userid': 'last', 'sjs_jvmserver_change_agent': 'last',
                         'sjs_jvmserver_install_agent': 'last', 'sjs_jvmserver_install_time': 'last',
                         'sjs_jvmserver_install_userid': 'last', 'sjs_jvmserver_sys_use_count': 'sum',
                         'sjs_jvmserver_sys_waited': 'sum', 'sjs_jvmserver_sys_waited_time': 'sum',
                         'sjs_jvmserver_sys_wait_cur': 'sum', 'sjs_jvmserver_sys_wait_hwm': 'max',
                         'sjs_jvmserver_jvm_creation_gmt': 'last', 'sjs_jvmserver_jvm_creation_lcl': 'last',
                         'sjs_jvmserver_current_heap': 'last', 'sjs_jvmserver_initial_heap': 'last',
                         'sjs_jvmserver_max_heap': 'max', 'sjs_jvmserver_peak_heap': 'max',
                         'sjs_jvmserver_occupancy': 'max', 'sjs_jvmserver_gc_policy': 'last',
                         'sjs_jvmserver_mjr_gc_events': 'sum', 'sjs_jvmserver_mjr_gc_cpu': 'sum',
                         'sjs_jvmserver_mjr_heap_freed': 'max', 'sjs_jvmserver_mnr_gc_events': 'sum',
                         'sjs_jvmserver_mnr_gc_cpu': 'sum', 'sjs_jvmserver_mnr_heap_freed': 'max',
                         'sjs_jvmserver_code_cache_used': 'max', 'sjs_jvmserver_code_cache_alloc': 'max',
                         'sjs_jvmserver_data_cache_used': 'max', 'sjs_jvmserver_data_cache_alloc': 'max',
                         'sjs_jvmserver_class_strg_used': 'max', 'sjs_jvmserver_class_strg_alloc': 'max',
                         'sjs_jvmserver_classcache_size': 'last', 'sjs_jvmserver_classcache_free': 'max'},
            "dfhpiwds": {'piwds_len': 'last', 'piwds_id': 'last', 'piwds_vers': 'last', 'piw_program_interface': 'last',
                         'piw_msg_validation': 'last', 'piw_pipeline_name': 'last', 'piw_urimap_name': 'last',
                         'piw_wsbind_file': 'last', 'piw_wsdl_file': 'last', 'piw_wsdl_binding': 'last',
                         'piw_endpoint_uri': 'last', 'piw_webservice_program': 'last', 'piw_container_name': 'last',
                         'piw_webservice_use_count': 'sum', 'piw_archive_file': 'last',
                         'piw_webservice_define_source': 'last', 'piw_webservice_change_time': 'last',
                         'piw_webservice_change_userid': 'last', 'piw_webservice_change_agent': 'last',
                         'piw_webservice_install_agent': 'last', 'piw_webservice_install_time': 'last',
                         'piw_webservice_install_userid': 'last'},
            "dfha21ds": {'a21_stats_length': 'last', 'a21_stats_id': 'last', 'a21_stats_version': 'last',
                         'a21_sit_luit_time': 'sum', 'a21_luit_total_reuses': 'sum', 'a21_luit_total_timeouts': 'sum',
                         'a21_luit_av_reuse_time': 'mean'},
            "dfhxmcds": {'xmclen': 'last', 'xmcid': 'last', 'xmcdvers': 'last', 'xmctat': 'sum', 'xmcpi': 'sum',
                         'xmctq': 'sum', 'xmcai': 'sum', 'xmcaaq': 'sum', 'xmcpwq': 'sum', 'xmcmxt': 'max',
                         'xmcth': 'last', 'xmcitd': 'last', 'xmcpat': 'max', 'xmcpqt': 'max', 'xmctama': 'sum',
                         'xmctapt': 'sum', 'xmccat': 'last', 'xmccqt': 'last', 'xmctqtme': 'sum', 'xmccqtme': 'sum',
                         'xmcgama': 'last', 'xmcpua': 'last', 'xmc_tclass_define_source': 'last',
                         'xmc_tclass_change_time': 'last', 'xmc_tclass_change_userid': 'last',
                         'xmc_tclass_change_agent': 'last', 'xmc_tclass_install_agent': 'last',
                         'xmc_tclass_install_time': 'last', 'xmc_tclass_install_userid': 'last'},
            "dfhtsgds": {'tsglen': 'last', 'tsgid': 'last', 'tsgdvers': 'last', 'tsgsta5f': 'sum', 'tsgnmg': 'sum',
                         'tsgsta7f': 'sum', 'tsgnag': 'sum', 'tsgqnumh': 'max', 'tsgqinh': 'max', 'tsgsta3f': 'sum',
                         'tsgcsz': 'last', 'tsgstabf': 'sum', 'tsgnci': 'last', 'tsgnciah': 'last', 'tsgsta8f': 'sum',
                         'tsgnbca': 'last', 'tsgbwtn': 'sum', 'tsgbuwth': 'max', 'tsgtwtn': 'sum', 'tsgtwtnr': 'sum',
                         'tsgtrdn': 'sum', 'tsgtwtnf': 'sum', 'tsgnvca': 'max', 'tsgnvcah': 'max', 'tsgvwtn': 'sum',
                         'tsgvuwth': 'max', 'tsgstaaf': 'sum', 'tsgsta9f': 'sum', 'tsgncia': 'last', 'tsgvuwt': 'sum',
                         'tsgbuwt': 'sum', 'tsgqnum': 'last', 'tsglar': 'max', 'tsgnavb': 'mean', 'tsgspci': 'mean',
                         'tsgbpseg': 'mean', 'tsgshpdf': 'max', 'tsgshpcn': 'max', 'tsgshrds': 'sum', 'tsgshwts': 'sum',
                         'tsgtslht': 'sum', 'tsgtsmlm': 'last', 'tsgtsmus': 'last', 'tsgtsmax': 'max',
                         'tsgtsqdl': 'sum',
                         'tsgtsctr': 'sum', 'tsgasu': 'last', 'tsgasupk': 'max'},
            "dfha04ds": {'a04len': 'last', 'a04id': 'last', 'a04dvers': 'last', 'a04vadat': 'sum', 'a04vadsh': 'sum',
                         'a04vadrj': 'sum', 'a04vadlo': 'sum', 'a04vadpk': 'max', 'a04vadpx': 'sum', 'a04vadqt': 'sum',
                         'a04vadqk': 'max', 'a04vadqx': 'sum', 'a04rdint': 'last', 'a04rdidl': 'last',
                         'a04skblt': 'sum',
                         'a04skins': 'sum', 'a04skdel': 'sum', 'a04tiexp': 'sum', 'a04rdrec': 'sum', 'a04rdiss': 'sum',
                         'a04rddel': 'sum', 'a04cidct': 'last', 'a04cidle': 'last', 'a04cmaxi': 'last',
                         'a04tidct': 'sum', 'a04tidle': 'sum', 'a04tmaxi': 'max'},
            "dfheccds": {'eccds_len': 'last', 'eccds_id': 'last', 'eccds_vers': 'last', 'ecc_capturespec_name': 'last',
                         'ecc_capture_point_type': 'last', 'ecc_capture_point': 'last', 'ecc_event_name': 'last',
                         'ecc_events_captured': 'sum', 'ecc_capture_failures': 'sum'},
            "dfhrlrds": {'rlrds_len': 'last', 'rlrds_id': 'last', 'rlrds_vers': 'last', 'rlr_bundle_directory': 'last',
                         'rlr_bundle_basescope': 'last', 'rlr_bundle_define_source': 'last',
                         'rlr_bundle_change_time': 'last', 'rlr_bundle_change_userid': 'last',
                         'rlr_bundle_change_agent': 'last', 'rlr_bundle_install_agent': 'last',
                         'rlr_bundle_install_time': 'last', 'rlr_bundle_install_userid': 'last'},
            "smtbody": {'smtlocn': 'last', 'smtaccess': 'last', 'smtdsaindex': 'last', 'smtgmreq': 'sum',
                        'smtfmreq': 'sum', 'smtces': 'last', 'smtcps': 'last', 'smtcne': 'last', 'smthwmps': 'max'},
            "dfhnqgds": {'nqglen': 'last', 'nqgid': 'last', 'nqgdvers': 'last', 'nqgnpool': 'last'},
            "dfhdsgds": {'dsglen': 'last', 'dsgid': 'last', 'dsgdvers': 'last', 'dsgglen': 'last', 'dsgasize': 'last',
                         'dsgpsize': 'last', 'dsgicvt': 'last', 'dsgicvrt': 'last', 'dsgicvsd': 'last',
                         'dsgpriag': 'last', 'dsgstsks': 'last', 'dsgmbtch': 'last', 'dsgcnt': 'last', 'dsgpnt': 'max',
                         'dsgstart': 'last', 'dsglstrt': 'last', 'dsgejst': 'sum', 'dsgsrbt': 'sum', 'dsgxscns': 'sum',
                         'dsgxscnn': 'sum', 'dsgxtcbd': 'sum', 'dsggxscn': 'last', 'dsglxscn': 'last',
                         'dsggxsnd': 'last', 'dsglxsnd': 'last'},
            "dfhxqs1d": {'s1len': 'last', 's1id': 'last', 's1dvers': 'last', 's1pref': 'last', 's1cnpref': 'last',
                         's1cnsysn': 'last', 's1size': 'last', 's1sizemx': 'max', 's1hdrs': 'max', 's1hdrsct': 'last',
                         's1hdrsqd': 'max', 's1elemln': 'last', 's1elempw': 'last', 's1elempe': 'max',
                         's1elemrt': 'last', 's1entrrt': 'last', 's1entrct': 'last', 's1entrhi': 'max',
                         's1entrlo': 'min', 's1entrmx': 'max', 's1elemct': 'last', 's1elemhi': 'max', 's1elemlo': 'min',
                         's1elemmx': 'max', 's1usedct': 'last', 's1usedhi': 'max', 's1freect': 'last',
                         's1freehi': 'max',
                         's1indxct': 'last', 's1indxhi': 'max', 's1rdqct': 'sum', 's1wrqct': 'sum', 's1dlqct': 'sum',
                         's1crlct': 'sum', 's1dllct': 'sum', 's1rdlct': 'sum', 's1wrlct': 'sum', 's1rwlct': 'sum',
                         's1inqct': 'sum', 's1inlct': 'sum', 's1wract': 'sum', 's1rrqct': 'sum', 's1rrlct': 'sum',
                         's1asyct': 'sum', 's1rsp1ct': 'sum', 's1rsp2ct': 'sum', 's1rsp3ct': 'sum', 's1rsp4ct': 'sum',
                         's1rsp5ct': 'sum', 's1rsp6ct': 'sum', 's1rsp7ct': 'sum', 's1rsp8ct': 'sum', 's1rsp9ct': 'sum'},
            "dfhcfs8d": {'s8len': 'last', 's8id': 'last', 's8dvers': 'last', 's8ocopen': 'sum', 's8occlos': 'sum',
                         's8ocset': 'sum', 's8ocdele': 'sum', 's8ocstat': 'sum', 's8rqpoin': 'sum', 's8rqhigh': 'sum',
                         's8rqread': 'sum', 's8rqrddl': 'sum', 's8rqunlk': 'sum', 's8rqload': 'sum', 's8rqwrit': 'sum',
                         's8rqrewr': 'sum', 's8rqdele': 'sum', 's8rqdelm': 'sum', 's8iqinqu': 'sum', 's8spprep': 'sum',
                         's8spreta': 'sum', 's8spcomm': 'sum', 's8spback': 'sum', 's8spinqu': 'sum', 's8sprest': 'sum'},
            "dfhtdrds": {'tdrlen': 'last', 'tdrid': 'last', 'tdrdvers': 'last', 'tdrstkn': 'sum', 'tdrssupr': 'sum',
                         'tdrttkn': 'sum', 'tdrtsupr': 'sum'},
            "dfhsjnds": {'sjnds_len': 'last', 'sjnds_id': 'last', 'sjnds_vers': 'last',
                         'sjn_nodejsapp_le_runopts': 'last', 'sjn_nodejsapp_state': 'last',
                         'sjn_nodejsapp_define_source': 'last', 'sjn_nodejsapp_change_time': 'last',
                         'sjn_nodejsapp_change_userid': 'last', 'sjn_nodejsapp_change_agent': 'last',
                         'sjn_nodejsapp_install_agent': 'last', 'sjn_nodejsapp_install_time': 'last',
                         'sjn_nodejsapp_install_userid': 'last', 'sjn_nodejsapp_creation_lcl': 'last',
                         'sjn_nodejsapp_pid': 'sum', 'sjn_nodejsapp_bundle_name': 'last', 'sjn_nodejsapp_cpu': 'sum',
                         'sjn_nodejsapp_heap_current': 'last', 'sjn_nodejsapp_heap_runtime': 'max',
                         'sjn_nodejsapp_heap_app_data': 'max', 'sjn_nodejsapp_heap_max': 'max',
                         'sjn_nodejsapp_invk': 'sum', 'sjn_nodejsapp_invk_err': 'sum', 'sjn_nodejsapp_invk_cur': 'last',
                         'sjn_nodejsapp_invk_peak': 'max', 'sjn_nodejsapp_nodehome': 'last',
                         'sjn_nodejsapp_profile': 'last', 'sjn_nodejsapp_startscrit': 'last',
                         'sjn_nodejsapp_stderr': 'last', 'sjn_nodejsapp_stdout': 'last', 'sjn_nodejsapp_trace': 'last',
                         'sjn_nodejsapp_log': 'last'},
            "dfhlgsds": {'lgslen': 'last', 'lgsid': 'last', 'lgsdvers': 'last', 'lgswrites': 'sum', 'lgsbytes': 'sum',
                         'lgscufwtrs': 'last', 'lgspkfwtrs': 'max', 'lgstfcwait': 'sum', 'lgsbufwait': 'sum',
                         'lgsbrwstrt': 'sum', 'lgsbrwread': 'sum', 'lgsdeletes': 'sum', 'lgsrtyerrs': 'sum',
                         'lgsbufapp': 'sum', 'lgssyslg': 'last', 'lgsdonly': 'last', 'lgsstruc': 'last',
                         'lgsmaxbl': 'max', 'lgsretpd': 'last', 'lgsautod': 'last', 'lgsqueries': 'sum'},
            "dfhsmdds": {'smdlen': 'last', 'smdid': 'last', 'smddvers': 'last', 'smddsaname': 'last',
                         'smdetype': 'last',
                         'smdflen': 'last', 'smdelchn': 'last', 'smdbndry': 'last', 'smdlocn': 'last',
                         'smdaccess': 'last', 'smddsaindex': 'last', 'smdifree': 'last', 'smdgmreq': 'sum',
                         'smdfmreq': 'sum', 'smdces': 'last', 'smdcps': 'last', 'smdcelem': 'last', 'smdhwmps': 'max'},
            "dfhldyds": {'ldyds_len': 'last', 'ldyds_id': 'last', 'ldyds_vers': 'last',
                         'ldy_library_appl_major_ver': 'last', 'ldy_library_appl_minor_ver': 'last',
                         'ldy_library_appl_micro_ver': 'last', 'ldy_library_name': 'last',
                         'ldy_library_search_pos': 'last', 'ldy_library_ranking': 'last',
                         'ldy_library_critical': 'last',
                         'ldy_library_enable_status': 'last', 'ldy_library_prog_loads': 'sum',
                         'ldy_library_define_source': 'last', 'ldy_library_change_time': 'last',
                         'ldy_library_change_userid': 'last', 'ldy_library_change_agent': 'last',
                         'ldy_library_install_agent': 'last', 'ldy_library_install_time': 'last',
                         'ldy_library_install_userid': 'last', 'ldy_library_numdsnames': 'last'},
            "ldgdsastat": {'ldgstgniu': 'max', 'ldgprogniu': 'max', 'ldgrecniu': 'max', 'ldgdpscr': 'max',
                           'ldgdpsct': 'sum'},
            "dfhpgpds": {'pgpds_len': 'last', 'pgpds_id': 'last', 'pgpds_vers': 'last',
                         'pgp_jvmprogram_appl_major_ver': 'last', 'pgp_jvmprogram_appl_minor_ver': 'last',
                         'pgp_jvmprogram_appl_micro_ver': 'last', 'pgp_jvmprogram_name': 'last',
                         'pgp_jvmprogram_entrypoint': 'last', 'pgp_jvmprogram_usecount': 'sum',
                         'pgp_jvmprogram_exec_key': 'last', 'pgp_jvmprogram_jvmclass': 'last',
                         'pgp_jvmprogram_server': 'last', 'pgp_jvmprogram_operation_name': 'last'},
            "dfhsords": {'sords_len': 'last', 'sords_id': 'last', 'sords_vers': 'last', 'sor_trans_attached': 'sum',
                         'sor_current_conns': 'last', 'sor_peak_conns': 'max', 'sor_open_gmt': 'last',
                         'sor_open_local': 'last', 'sor_close_gmt': 'last', 'sor_close_local': 'last',
                         'sor_port_number': 'last', 'sor_ssl_support': 'last', 'sor_backlog': 'last',
                         'sor_sends': 'sum',
                         'sor_bytes_sent': 'sum', 'sor_receives': 'sum', 'sor_bytes_received': 'sum',
                         'sor_wlm_group': 'last', 'sor_protocol': 'last', 'sor_authenticate': 'last',
                         'sor_privacy': 'last', 'sor_attachsec': 'last', 'sor_maxdata_length': 'last',
                         'sor_tcpips_tranid': 'last', 'sor_tcpips_urm': 'last', 'sor_tcpips_max_persist': 'last',
                         'sor_tcpips_non_persist': 'sum', 'sor_ip_address': 'last', 'sor_ip_family': 'last',
                         'sor_hostname': 'last', 'sor_define_source': 'last', 'sor_change_time': 'last',
                         'sor_change_userid': 'last', 'sor_change_agent': 'last', 'sor_install_agent': 'last',
                         'sor_install_time': 'last', 'sor_install_userid': 'last', 'sor_total_conns': 'sum',
                         'sor_nonp_at_maxpersist': 'sum', 'sor_nonp_at_task_limit': 'sum',
                         'sor_disc_at_task_limit': 'sum', 'sor_disc_at_max_uses': 'sum', 'sor_curr_backlog': 'last',
                         'sor_conns_dropped': 'sum', 'sor_conn_last_dropped': 'last', 'sor_curr_max_backlog': 'last',
                         'sor_requests': 'sum', 'sor_tcpips_optionspgm': 'last'},
            "dfhncs5d": {'s5len': 'last', 's5id': 'last', 's5dvers': 'last', 's5anynam': 'last', 's5anysiz': 'last',
                         's5anyptr': 'last', 's5anymx': 'max', 's5anyus': 'max', 's5anyfr': 'max', 's5anylo': 'min',
                         's5anyrqg': 'sum', 's5anyrqf': 'sum', 's5anyrqs': 'sum', 's5anyrqc': 'sum', 's5lownam': 'last',
                         's5lowsiz': 'last', 's5lowptr': 'last', 's5lowmx': 'max', 's5lowus': 'max', 's5lowfr': 'max',
                         's5lowlo': 'min', 's5lowrqg': 'sum', 's5lowrqf': 'sum', 's5lowrqs': 'sum', 's5lowrqc': 'sum'},
            "dfhlgrds": {'lgrlen': 'last', 'lgrid': 'last', 'lgrdvers': 'last', 'lgrjtype': 'last', 'lgrstream': 'last',
                         'lgrwrites': 'sum', 'lgrbytes': 'sum', 'lgrbuflsh': 'sum'},
            "dfhecgds": {'ecgds_len': 'last', 'ecgds_id': 'last', 'ecgds_vers': 'last',
                         'ecg_eb_event_filter_ops': 'sum',
                         'ecg_eb_events_captured': 'sum', 'ecg_eb_events_disabled': 'sum',
                         'ecg_sys_events_captured': 'sum', 'ecg_filter_ops_failed': 'sum',
                         'ecg_capture_ops_failed': 'sum'},
            "dfhecrds": {'ecrds_len': 'last', 'ecrds_id': 'last', 'ecrds_vers': 'last', 'ecr_epadapter_name': 'last',
                         'ecr_eb_define_source': 'last', 'ecr_eb_change_time': 'last', 'ecr_eb_change_userid': 'last',
                         'ecr_eb_change_agent': 'last', 'ecr_eb_install_agent': 'last', 'ecr_eb_install_time': 'last',
                         'ecr_eb_install_userid': 'last'},
            "dfhlggds": {'lgglen': 'last', 'lggid': 'last', 'lggdvers': 'last', 'lggakpfreq': 'last',
                         'lgglgdefer': 'last', 'lggakpstkn': 'sum'},
            "dfhmngds": {'mnglen': 'last', 'mngid': 'last', 'mngdvers': 'last', 'mnger': 'sum', 'mngers': 'sum',
                         'mngpr': 'sum', 'mngprs': 'sum', 'mngsmfr': 'sum', 'mngsmfe': 'sum', 'mngsmfnc': 'sum',
                         'mngsmfcm': 'sum', 'mngrr': 'sum', 'mngrrs': 'sum', 'mngir': 'sum', 'mngirs': 'sum',
                         'mngfrl': 'last', 'mngtrl': 'last', 'mngdplrl': 'last', 'mngurirl': 'last', 'mngwebrl': 'last',
                         'mngrmi': 'last', 'mngappns': 'last', 'mngmrcmp': 'last', 'mngavurl': 'mean',
                         'mngavcrl': 'mean', 'mngwlmmd': 'last', 'mngwlmst': 'last', 'mngwlmsc': 'last',
                         'mngwlmwn': 'last', 'mngwlmrg': 'last', 'mngwlmrc': 'last', 'mngwlmgt': 'last',
                         'mngwlmcc': 'last', 'mngwlmsk': 'last', 'mngwlmgm': 'last', 'mngwlmgv': 'last',
                         'mngwlmgi': 'last', 'mngcectp': 'last', 'mngcecid': 'last', 'mngmctnm': 'last',
                         'mngutnum': 'sum', 'mngstnum': 'sum', 'mnggutcl': 'last', 'mnglutcl': 'last',
                         'mnggutat': 'last', 'mnglutat': 'last', 'mngmxuta': 'last', 'mngcauta': 'last',
                         'mngfreq': 'last', 'mngautrt': 'mean', 'mngputrt': 'max', 'mnggutrt': 'last',
                         'mnglutrt': 'last', 'mngcput': 'sum', 'mngtoncp': 'sum', 'mngoflcp': 'sum'},
            "dfhd2gds": {'d2glen': 'last', 'd2gid': 'last', 'd2gdvers': 'last', 'd2g_db2conn_name': 'last',
                         'd2g_db2_id': 'last', 'd2g_db2_release': 'last', 'd2g_connect_time_gmt': 'last',
                         'd2g_connect_time_local': 'last', 'd2g_disconnect_time_gmt': 'last',
                         'd2g_disconnect_time_local': 'last', 'd2g_tcb_limit': 'last', 'd2g_tcb_current': 'last',
                         'd2g_tcb_hwm': 'max', 'd2g_tcb_free': 'last', 'd2g_tcb_readyq_current': 'last',
                         'd2g_tcb_readyq_hwm': 'max', 'd2g_db2_group_id': 'last', 'd2g_resyncmember': 'last',
                         'd2g_reuselimit': 'last', 'd2g_tcb_protected_current': 'last', 'd2g_pool_plan_name': 'last',
                         'd2g_pool_planexit_name': 'last', 'd2g_pool_authid': 'last', 'd2g_pool_authtype': 'last',
                         'd2g_pool_accountrec': 'last', 'd2g_pool_threadwait': 'last', 'd2g_pool_priority': 'last',
                         'd2g_pool_calls': 'sum', 'd2g_pool_signons': 'sum', 'd2g_pool_commits': 'sum',
                         'd2g_pool_aborts': 'sum', 'd2g_pool_single_phase': 'sum', 'd2g_pool_thread_reuse': 'sum',
                         'd2g_pool_thread_term': 'sum', 'd2g_pool_thread_waits': 'sum', 'd2g_pool_thread_limit': 'last',
                         'd2g_pool_thread_current': 'last', 'd2g_pool_thread_hwm': 'max',
                         'd2g_pool_task_current': 'last', 'd2g_pool_task_hwm': 'max', 'd2g_pool_task_total': 'sum',
                         'd2g_pool_readyq_current': 'last', 'd2g_pool_readyq_hwm': 'max',
                         'd2g_pool_partial_signons': 'sum', 'd2g_pool_thread_create': 'sum',
                         'd2g_pool_reuselimit_count': 'sum', 'd2g_comd_authid': 'last', 'd2g_comd_authtype': 'last',
                         'd2g_comd_calls': 'sum', 'd2g_comd_signons': 'sum', 'd2g_comd_thread_term': 'sum',
                         'd2g_comd_thread_overf': 'sum', 'd2g_comd_thread_limit': 'last',
                         'd2g_comd_thread_current': 'last', 'd2g_comd_thread_hwm': 'max',
                         'd2g_comd_thread_create': 'sum', 'd2g_db2conn_define_source': 'last',
                         'd2g_db2conn_change_time': 'last', 'd2g_db2conn_change_userid': 'last',
                         'd2g_db2conn_change_agent': 'last', 'd2g_db2conn_install_agent': 'last',
                         'd2g_db2conn_install_time': 'last', 'd2g_db2conn_install_userid': 'last'},
            "dfhldpds": {'ldplen': 'last', 'ldpid': 'last', 'ldpdvers': 'last', 'ldp_appl_major_ver': 'last',
                         'ldp_appl_minor_ver': 'last', 'ldp_appl_micro_ver': 'last', 'ldppname': 'last', 'ldptu': 'sum',
                         'ldpfc': 'sum', 'ldpft': 'sum', 'ldptn': 'sum', 'ldppsize': 'last', 'ldprpc': 'sum',
                         'ldplocn': 'last', 'ldplbnm': 'last', 'ldplbdnm': 'last', 'ldp_operation_name': 'last'},
            "dfhxqs3d": {'s3len': 'last', 's3id': 'last', 's3dvers': 'last', 's3anynam': 'last', 's3anysiz': 'last',
                         's3anyptr': 'last', 's3anymx': 'max', 's3anyus': 'max', 's3anyfr': 'max', 's3anylo': 'min',
                         's3anyrqg': 'sum', 's3anyrqf': 'sum', 's3anyrqs': 'sum', 's3anyrqc': 'sum', 's3lownam': 'last',
                         's3lowsiz': 'last', 's3lowptr': 'last', 's3lowmx': 'max', 's3lowus': 'max', 's3lowfr': 'max',
                         's3lowlo': 'min', 's3lowrqg': 'sum', 's3lowrqf': 'sum', 's3lowrqs': 'sum', 's3lowrqc': 'sum'},
            "dfhd2rds": {'d2rlen': 'last', 'd2rid': 'last', 'd2rdvers': 'last', 'd2r_plan_name': 'last',
                         'd2r_planexit_name': 'last', 'd2r_authid': 'last', 'd2r_authtype': 'last',
                         'd2r_accountrec': 'last', 'd2r_threadwait': 'last', 'd2r_priority': 'last', 'd2r_calls': 'sum',
                         'd2r_signons': 'sum', 'd2r_commits': 'sum', 'd2r_aborts': 'sum', 'd2r_single_phase': 'sum',
                         'd2r_thread_reuse': 'sum', 'd2r_thread_term': 'sum', 'd2r_thread_wait_or_overfl': 'sum',
                         'd2r_thread_limit': 'last', 'd2r_thread_current': 'last', 'd2r_thread_hwm': 'max',
                         'd2r_pthread_limit': 'last', 'd2r_pthread_current': 'last', 'd2r_pthread_hwm': 'max',
                         'd2r_task_current': 'last', 'd2r_task_hwm': 'max', 'd2r_task_total': 'sum',
                         'd2r_readyq_current': 'last', 'd2r_readyq_hwm': 'max', 'd2r_partial_signons': 'sum',
                         'd2r_thread_create': 'sum', 'd2r_reuselimit_count': 'sum', 'd2r_sharelocks': 'last',
                         'd2r_define_source': 'last', 'd2r_change_time': 'last', 'd2r_change_userid': 'last',
                         'd2r_change_agent': 'last', 'd2r_install_agent': 'last', 'd2r_install_time': 'last',
                         'd2r_install_userid': 'last'},
            "dfhstgds": {'stglen': 'last', 'stgid': 'last', 'stgdvers': 'last', 'stgnc': 'sum', 'stgsmfw': 'sum',
                         'stgldw': 'sum', 'stgsmfs': 'sum', 'stgsmfe': 'sum', 'stgintr': 'sum', 'stgeodr': 'sum',
                         'stgussr': 'sum', 'stgreqr': 'sum', 'stgrrtr': 'sum', 'stgcstrt': 'last', 'stglrt': 'last',
                         'stgintvl': 'last', 'stgeodt': 'last', 'stgstrcd': 'last'},
            "dfhsogds": {'sogds_len': 'last', 'sogds_id': 'last', 'sogds_vers': 'last', 'sog_maxsockets_limit': 'last',
                         'sog_curr_inbound_sockets': 'last', 'sog_peak_inbound_sockets': 'max',
                         'sog_curr_outb_sockets': 'last', 'sog_peak_outb_sockets': 'max',
                         'sog_inb_sockets_created': 'sum', 'sog_outb_sockets_created': 'sum',
                         'sog_outb_sockets_closed': 'sum', 'sog_times_at_max_sockets': 'sum',
                         'sog_delayed_at_max_sockets': 'sum', 'sog_qtime_at_max_sockets': 'sum',
                         'sog_timedout_at_max_sockets': 'sum', 'sog_curr_delayed_at_max': 'last',
                         'sog_peak_delayed_at_max': 'max', 'sog_current_qtime_at_max': 'last', 'sog_sslcache': 'last',
                         'sog_sotuning': 'last', 'sog_pausing_http_listening': 'last',
                         'sog_stopping_persistence': 'last', 'sog_times_at_accept_limit': 'sum',
                         'sog_time_last_paused_http_listening': 'last', 'sog_times_stopped_persistent': 'sum',
                         'sog_time_last_stopped_persistent': 'last', 'sog_times_made_non_persistent': 'sum',
                         'sog_times_conn_disconnected_at_max': 'sum', 'sog_peak_pers_inb_sockets': 'max',
                         'sog_peak_npers_inb_sockets': 'max', 'sog_curr_npers_inb_sockets': 'last',
                         'sog_npers_inb_sockets_created': 'sum', 'sog_times_outb_reused': 'sum',
                         'sog_s8tlshs_requests_max': 'max', 'sog_s8tlshs_requests_cur': 'last',
                         'sog_s8tlshs_requests_peak': 'max', 'sog_s8tlshs_waiters_max': 'max',
                         'sog_s8tlshs_waiters_cur': 'last', 'sog_s8tlshs_waiters_peak': 'max',
                         'sog_times_cicstls12_inb_used': 'sum', 'sog_times_cicstls13_inb_used': 'sum',
                         'sog_times_cicstlsall_inb_used': 'sum', 'sog_times_cicstls12_outb_used': 'sum',
                         'sog_times_cicstls13_outb_used': 'sum', 'sog_times_cicstlsall_outb_used': 'sum',
                         'sog_times_atssl3_inb_used': 'sum', 'sog_times_attls10_inb_used': 'sum',
                         'sog_times_attls11_inb_used': 'sum', 'sog_times_attls12_inb_used': 'sum',
                         'sog_times_attls13_inb_used': 'sum', 'sog_times_atssl3_outb_used': 'sum',
                         'sog_times_attls10_outb_used': 'sum', 'sog_times_attls11_outb_used': 'sum',
                         'sog_times_attls12_outb_used': 'sum', 'sog_times_attls13_outb_used': 'sum',
                         'sog_handshakes_full_inb': 'sum', 'sog_handshakes_abbrev_inb': 'sum',
                         'sog_handshakes_full_outb': 'sum', 'sog_handshakes_abbrev_outb': 'sum'},
            "dfhxqs2d": {'s2len': 'last', 's2id': 'last', 's2dvers': 'last', 's2bfqty': 'last', 's2bfenth': 'last',
                         's2bfacts': 'last', 's2bflrus': 'last', 's2bfemps': 'last', 's2bfpwts': 'sum',
                         's2bfgets': 'sum', 's2bfhits': 'sum', 's2bfgfrs': 'sum', 's2bfgnws': 'sum', 's2bfglrs': 'sum',
                         's2bflwts': 'sum', 's2bfgnbs': 'sum', 's2bfputs': 'sum', 's2bfkeps': 'sum', 's2bffres': 'sum',
                         's2bffnos': 'sum', 's2bfpurs': 'sum', 's2bfpnfs': 'sum', 's2bfpnos': 'sum'},
            "dfhpggds": {'pgg_stats_length': 'last', 'pgg_stats_id': 'last', 'pgg_stats_version': 'last',
                         'pgg_auto_attempts': 'sum', 'pgg_auto_rejects': 'sum', 'pgg_auto_failures': 'sum'},
            "dfhcfs9d": {'s9len': 'last', 's9id': 'last', 's9dvers': 'last', 's9anynam': 'last', 's9anysiz': 'last',
                         's9anyptr': 'last', 's9anymx': 'max', 's9anyus': 'max', 's9anyfr': 'max', 's9anylo': 'min',
                         's9anyrqg': 'sum', 's9anyrqf': 'sum', 's9anyrqs': 'sum', 's9anyrqc': 'sum', 's9lownam': 'last',
                         's9lowsiz': 'last', 's9lowptr': 'last', 's9lowmx': 'max', 's9lowus': 'max', 's9lowfr': 'max',
                         's9lowlo': 'min', 's9lowrqg': 'sum', 's9lowrqf': 'sum', 's9lowrqs': 'sum', 's9lowrqc': 'sum'},
            "dsgtcbm": {'dsgtcbmd': 'last', 'dsgtcbmp': 'last', 'dsgntcba': 'sum', 'dsgtcbaf': 'sum',
                        'dsgtcbca': 'last',
                        'dsgtcbpa': 'max', 'dsgtcbcu': 'last', 'dsgtcbpu': 'max', 'dsgtcbal': 'sum', 'dsgtcbdu': 'sum',
                        'dsgtcbds': 'sum', 'dsgtcbdx': 'sum', 'dsgtcbdo': 'sum', 'dsgtcbst': 'sum', 'dsgtcbmm': 'sum',
                        'dsgsysw': 'sum', 'dsgtmcdq': 'last', 'dsgtmpdq': 'max', 'dsgtmadq': 'mean', 'dsgtwt': 'sum',
                        'dsgtdt': 'sum', 'dsgtct': 'sum', 'dsgact': 'sum'},
            "dfhncs4d": {'s4len': 'last', 's4id': 'last', 's4dvers': 'last', 's4pref': 'last', 's4cnpref': 'last',
                         's4cnsysn': 'last', 's4size': 'last', 's4sizemx': 'max', 's4entrct': 'last', 's4entrhi': 'max',
                         's4entrlo': 'min', 's4entrmx': 'max', 's4crect': 'sum', 's4getct': 'sum', 's4setct': 'sum',
                         's4delct': 'sum', 's4keqct': 'sum', 's4kgect': 'sum', 's4asyct': 'sum', 's4rsp1ct': 'sum',
                         's4rsp2ct': 'sum', 's4rsp3ct': 'sum', 's4rsp4ct': 'sum', 's4rsp5ct': 'sum', 's4rsp6ct': 'sum',
                         's4rsp7ct': 'sum'},
            "dfhrmgds": {'rmglen': 'last', 'rmgid': 'last', 'rmgdvers': 'last', 'rmgsyfwd': 'sum', 'rmgsybwd': 'sum',
                         'rmgresyn': 'sum', 'rmgtshin': 'sum', 'rmgtshti': 'sum', 'rmgcshin': 'last',
                         'rmgcshti': 'last',
                         'rmgtshro': 'sum', 'rmgtshtr': 'sum', 'rmgcshro': 'last', 'rmgcshtr': 'last',
                         'rmgiaftr': 'sum',
                         'rmgiafti': 'sum', 'rmgiafnw': 'sum', 'rmgiafop': 'sum', 'rmgiafot': 'sum', 'rmgiamis': 'sum',
                         'rmgnwtd': 'sum', 'rmgnw61': 'sum', 'rmgnwmro': 'sum', 'rmgnwrmi': 'sum', 'rmgnwoth': 'sum'},
            "dfhusgds": {'usglen': 'last', 'usgid': 'last', 'usgdvers': 'last', 'usgtomrt': 'mean', 'usgtorc': 'sum',
                         'usgtoec': 'sum', 'usgdrrc': 'sum', 'usgdrnfc': 'sum', 'usgdesof': 'sum', 'usgdeenf': 'sum',
                         'usgdrcur': 'last', 'usgdrpk': 'max', 'usgtocur': 'last', 'usgtopk': 'max', 'usgenfk': 'sum',
                         'usgenfun': 'sum'}}
