import datetime as dt
from typing import Optional

import sqlalchemy as sa
import sqlalchemy.orm as so
from sqlalchemy.ext.declarative import AbstractConcreteBase


class ReprMixin(object):
    """A mixin to implement a generic __repr__ method"""

    def as_dict(self):
        """return instance as a dictionary"""
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self):
        return '<%s(%s)>' % (self.__class__.__name__,
                             ', '.join([f'{c.name} = {getattr(self, c.name)}' for c in self.__table__.primary_key]))


convention = {
    'all_column_names': lambda constraint, table: '_'.join(
        [column.name for column in constraint.columns.values()]
    ),
    'ix': 'ix__%(table_name)s__%(all_column_names)s',
    'uq': 'uq__%(table_name)s__%(all_column_names)s',
    'ck': 'ck__%(table_name)s__%(constraint_name)s',
    'fk': 'fk__%(table_name)s__%(all_column_names)s__%(referred_table_name)s',
    'pk': 'pk__%(table_name)s',
}


class Base(so.DeclarativeBase):
    pass


class Base71(Base):
    __abstract__ = True
    metadata = sa.MetaData(schema='smf71', naming_convention=convention)


class Base71Hr(Base):
    __abstract__ = True
    metadata = sa.MetaData(schema='smf71', naming_convention=convention)


class Base71Da(Base):
    __abstract__ = True
    metadata = sa.MetaData(schema='smf71', naming_convention=convention)


class Smf71pro(AbstractConcreteBase):
    """Abstract class for structure Smf71Pro - RMF proudct section."""

    smf71mfv: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer, doc="RMF version number.")
    smf71prd: so.Mapped[Optional[str]] = so.mapped_column(sa.String(8), doc="Product name ('RMF').")
    smf71int: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Duration of RMF measurement interval, in the form mmsstttF where mm is the minutes, ss is the seconds, ttt is the milliseconds, and F is the sign. The end of the measurement interval is the sum of the record start time (and this field).")
    smf71sam: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer, doc="Number of RMF samples.")
    smf71fla: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Flags Bit Meaning when set 0 Reserved. 1 Samples have been skipped. 2 Record was written by RMF Monitor III. 3 Interval was synchronized with SMF. 4 SMF record converted to lower service level. 5 SMF record converted to higher release or service level. 6 Running under an alternate virtual machine. 7 - 15")
    smf71cyc: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Sampling cycle length, in the form 000 ttttF , where tttt is the milliseconds and F is the sign (taken from CYCLE option). The range of values is 0.050 to 9.999 seconds.")
    smf71mvs: so.Mapped[Optional[str]] = so.mapped_column(sa.String(8),
                                                          doc="z/OS software level (consists of an acronym and the version, release, and modification level - ZV vvrrmm ).")
    smf71iml: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Indicates the type of processor complex on which data measurements were taken. Value Meaning 3 9672, zSeries")
    smf71prf: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Processor flags. Bit Meaning when set 0 The system has expanded storage 1 The system has ESCON channels in the configuration 2 There is an ESCON director in the configuration 3 System is running in z/Architecture mode 4 At least one zAAP is currently installed 5 At least one zIIP is currently installed 6 Enhanced DAT facility 1 available")
    smf71ptn: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="PR/SM partition number of the partition that wrote this record.")
    smf71srl: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="SMF record level change number. This field enables processing of SMF record level changes in an existing release.")
    smf71lgo: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Offset GMT to local time (STCK format).")
    smf71oil: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Original interval length as defined in the session or by SMF (in seconds).")
    smf71syn: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer, doc="SYNC value in seconds.")
    smf71gie: so.Mapped[Optional[dt.datetime]] = so.mapped_column(sa.DateTime,
                                                                  doc="Projected gathering interval end (STCK format) GMT time.")
    smf71xnm: so.Mapped[Optional[str]] = so.mapped_column(sa.String(8),
                                                          doc="Sysplex name as defined in parmlib member COUPLExx.")
    smf71snm: so.Mapped[Optional[str]] = so.mapped_column(sa.String(8),
                                                          doc="System name for current system as defined in parmlib member IEASYSxx SYSNAME parameter.")
    smf71flg: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="System indicator: Bit Meaning when set 0 New record format 1 Subtypes used 2 Reserved 3-6 Version indicators* 7 System is running in PR/SM mode. *See 'Standard and extended SMF record headers' on page")
    speed_boost: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                             doc="smf71fla (Bit 10) indcating speed boost was active during entire interval.")
    ziip_boost: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                            doc="smf71fla (Bit 9) indciating zIIP boost was active during entire interval.")


class Smf71pag(AbstractConcreteBase):
    """Abstract class for structure Smf71Pag - Paging data section."""

    smf71pin: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-VIO page-ins from auxiliary to central storage. This field includes page- ins required through page faults, specific page requests, and page fixes. It does not include page reclaims or page-ins for VIO data sets.")
    smf71pot: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-VIO page-outs from central to auxiliary storage. This field includes page-outs required through specific page requests and those pages stolen by the paging supervisor through infrequent use. It does not include page-outs for VIO data sets.")
    smf71ssq: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of address space swap sequences. (A swap sequence consists of an address space swap-out and swap-in.)")
    smf71sin: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of pages swapped in. This field includes: LSQA, fixed pages, and those pages that the real storage manager determined to be active when the address space was swapped in. It does not include page reclaims.")
    smf71sot: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of pages swapped out. This field includes: LSQA, private area fixed pages, and private area non-fixed changed pages.")
    smf71vin: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of VIO page-ins from auxiliary to central storage. This field includes page-ins resulting from page faults or specific page requests on a VIO window. It does not include VIO swap-ins or page-ins for the common area.")
    smf71vot: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of VIO page-outs from central to auxiliary storage. This field includes page- outs resulting from specific page requests on a VIO window and those pages stolen by the paging supervisor through infrequent use. It does not include VIO swap-outs or page-outs for the common area.")
    smf71sni: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-VIO page-ins (from auxiliary to central storage) performed in common area (LPA/CSA).")
    smf71sno: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-VIO page-outs (from central to auxiliary storage) performed in common area (LPA/CSA).")
    smf71lni: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-VIO page-ins performed in LPA.")
    smf71afc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="End-of-interval snapshot value of the number of unused central storage page frames.")
    smf71tfc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of page frames defined in central storage. (This field does not include frames occupied by the nucleus, frames marked as bad or offline, or frames used by HSA or PR/ SM.)")
    smf71tsc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Total number of local page data set slots.")
    smf71dsc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of local page data set slots allocated to VIO private area pages.")
    smf71vsc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of local page data set slots allocated to non-VIO private area pages.")
    smf71nsc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of usable local page data set slots that have not been allocated.")
    smf71fin: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of central storage frames in nucleus.")
    smf71mnf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of unused central storage page frames.")
    smf71mxf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of unused central storage page frames.")
    smf71avf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of unused central storage page frames.")
    smf71mnp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of CSA central storage frames used, including restricted use common service area (RUCSA).")
    smf71mxp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of CSA central storage frames used, including RUCSA.")
    smf71avp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of CSA central storage frames used, including RUCSA.")
    smf71mns: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of pageable address space central storage frames in the private address space.")
    smf71mxs: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of pageable address space central storage frames in the private address space.")
    smf71avs: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of pageable address space central storage frames in the private address space.")
    smf71mnt: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum total number of central storage frames used.")
    smf71mxt: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum total number of central storage frames used.")
    smf71avt: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average total number of central storage frames used.")
    smf71mnq: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of SQA fixed frames in central storage.")
    smf71mxq: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of SQA fixed frames in central storage.")
    smf71avq: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of SQA fixed frames in central storage.")
    smf71mnc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of CSA fixed frames in central storage, including RUCSA.")
    smf71mxc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of CSA fixed frames in central storage, including RUCSA.")
    smf71avc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of CSA fixed frames in central storage, including RUCSA.")
    smf71mnr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of non-LSQA fixed central storage frames in the private address space.")
    smf71mxr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of non-LSQA fixed central storage frames in the private address space.")
    smf71avr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of non-LSQA fixed central storage frames in the private address space.")
    smf71mnx: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum total number of fixed central storage frames used.")
    smf71mxx: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum total number of fixed central storage frames used.")
    smf71avx: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average total number of fixed central storage frames used.")
    smf71mnu: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of usable local page data set slots that have not been allocated.")
    smf71mxu: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of usable local page data set slots that have not been allocated.")
    smf71avu: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of usable local page data set slots that have not been allocated.")
    smf71mnv: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of local page data set slots allocated to VIO private area pages.")
    smf71mxv: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of local page data set slots allocated to VIO private area pages.")
    smf71avv: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of local page data set slots allocated to VIO private area pages.")
    smf71mnm: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of local page data set slots allocated to non-VIO private area pages.")
    smf71mxm: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of local page data set slots allocated to non-VIO private area pages.")
    smf71avm: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of local page data set slots allocated to non-VIO private area pages.")
    smf71mnb: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of unusable local page data set slots.")
    smf71mxb: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of unusable local page data set slots.")
    smf71avb: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of unusable local page data set slots.")
    smf71mna: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum total number of local page data set slots.")
    smf71mxa: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum total number of local page data set slots.")
    smf71is1: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of samples skipped due to invalid fixed frame counts. Fields affected are SMF71MNC, MXC, AVC, MNR, MXR, and AVR.")
    smf71is2: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of incorrect samples resulting from negative calculations. Fields affected are the same as SMF71IS1.")
    smf71nlp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of LPA frames in central storage.")
    smf71xlp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of LPA frames in central storage.")
    smf71alp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of LPA frames in central storage.")
    smf71nlf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of LPA fixed frames in central storage.")
    smf71xlf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of LPA fixed frames in central storage.")
    smf71alf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of LPA fixed frames in central storage.")
    smf71nls: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of LSQA fixed frames in central storage.")
    smf71xls: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of LSQA fixed frames in central storage.")
    smf71als: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of LSQA fixed frames in central storage.")
    smf71mnl: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of fixed frames in central storage (less than 16 megabytes).")
    smf71mxl: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of fixed frames in central storage (less than 16 megabytes).")
    smf71avl: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of fixed frames in central storage (less than 16 megabytes).")
    smf71pmv: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Total number of pages moved within central storage.")
    smf71opt: so.Mapped[Optional[str]] = so.mapped_column(sa.String(8), doc="SRM opt member name.")
    smf71lic: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum high UIC. A value from 0 to 2540 that indicates the age (in seconds) of the oldest unreferenced frame in central storage.")
    smf71hic: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum high UIC. A value from 0 to 2540 that indicates the age (in seconds) of the oldest unreferenced frame in central storage.")
    smf71aca: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average high UIC (scale factor= -1). Scale factor -1 means the field has been multiplied by 10 to give a result in tenths and must be multiplied by 10 -1 to get the correct value.")
    smf71msr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number SQA pages in central storage.")
    smf71xsr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number SQA pages in central storage.")
    smf71asr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of SQA pages in central storage.")
    smf71mlr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Minimum number of LSQA pages in central storage.")
    smf71xlr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Maximum number of LSQA pages in central storage.")
    smf71alr: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average number of LSQA pages in central storage.")
    smf71isc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of incorrect samples returned from collector service.")
    smf71hot: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of hiperspace page-outs from central to auxiliary storage.")
    smf71hin: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of hiperspace page-ins from auxiliary to central storage.")
    smf71blp: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of blocked pages paged in (this does not include VIO or hiperspace pages).")
    smf71blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger, doc="Number of blocks paged in.")
    smf71pmt: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Steal timer - the elapsed time spent in a preferred steal in CPU-timer units. The interval of CPU time needed to steal the page includes the time to move the contents of the stolen page and any time spent in frame steal processing of any type. Some examples of the types of steal routines whose CPU time gets included in SMF71PMT are non-preferred above, non- preferred below, preferred above, preferred below, storage buffer frame queue, bottom double frame queue, and V=R waiting frame. No matter what type of steal processing occurs, the steal module records it all, and it gets included in this field. Note that SMF71PMT does not include the time to move the new contents into the page.")
    smf71sbi: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of system pageable areas block page ins.")
    smf71lbi: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger, doc="Number of LPA block page ins.")
    smf71asi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of page-ins from auxiliary storage for shared pages.")
    smf71aso: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of page-outs to auxiliary storage for shared pages.")
    smf71mgt: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of shared pages in the system.")
    smf71xgt: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared pages in the system.")
    smf71agt: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages in the system.")
    smf71mgc: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Minimum number of shared pages in the")
    smf71xgc: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared pages in the central storage.")
    smf71agc: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages in the central storage.")
    smf71mga: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of auxiliary DASD slots in use for shared pages.")
    smf71xga: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of auxiliary DASD slots in use for shared pages.")
    smf71aga: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of auxiliary DASD slots in use for shared pages.")
    smf71mgf: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of shared pages fixed in the system.")
    smf71xgf: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared pages fixed in the system.")
    smf71agf: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages fixed in the system.")
    smf71mgb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of shared pages fixed below 16 MB in the system.")
    smf71xgb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared pages fixed below 16 MB in the system.")
    smf71agb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages fixed below 16 MB in the system.")
    smf71cam: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of available central storage frames.")
    smf71cax: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of available central storage frames.")
    smf71caa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of available central storage frames.")
    smf71clm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of low-impact central storage frames.")
    smf71clx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of low-impact central storage frames.")
    smf71cla: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of low-impact central storage frames.")
    smf71cmm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of medium-impact central storage frames.")
    smf71cmx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of medium-impact central storage frames.")
    smf71cma: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of medium-impact central storage frames.")
    smf71chm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high-impact central storage frames.")
    smf71chx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high-impact central storage frames.")
    smf71cha: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high-impact central storage frames.")
    smf71mvi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of VIO pages in central storage.")
    smf71xvi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of VIO pages in central storage.")
    smf71avi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of VIO pages in central storage.")
    smf71mhi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of hiperspace pages in central storage.")
    smf71xhi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of hiperspace pages in central storage.")
    smf71ahi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of hiperspace pages in central storage.")
    smf71vws: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of VIO pages written to central storage.")
    smf71vrs: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of VIO pages read from central storage.")
    smf71hws: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of hiperspace pages written to central storage.")
    smf71hrs: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of hiperspace pages read from central storage.")
    smf71mfb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of pages fixed between 16M and 2G.")
    smf71xfb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of pages fixed between 16M and 2G.")
    smf71afb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of pages fixed between 16M and 2G.")
    smf71pth: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of pages in the system used by shared memory objects.")
    smf71pch: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages in central storage (with virtual storage address above the bar including high virtual DAT).")
    smf71pah: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages in auxiliary storage (with virtual storage address above the bar).")
    smf71blg: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared bytes from large virtual memory in a memory object for the entire system.")
    smf71pih: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of page-ins from auxiliary storage for shared pages.")
    smf71poh: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Number of page-outs to auxiliary storage for shared pages (with virtual storage address above the bar).")
    smf71ulm: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Lowest minimum system UIC during the interval (from MCTMinSystemUIC).")
    smf71ulc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Lowest current system UIC during the interval (from MCTCurSystemUIC).")
    smf71uhc: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Highest current system UIC during the interval (from MCTCurSystemUIC).")
    smf71uhx: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Highest maximum system UIC during the interval (from MCTMaxSystemUIC).")
    smf71uam: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average minimum system UIC during the interval (from MCTMinSystemUIC).")
    smf71uac: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average current system UIC during the interval (from MCTCurSystemUIC).")
    smf71uax: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Average maximum system UIC during the interval (from MCTMaxSystemUIC).")
    smf71lom: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of fixed memory objects that are allocated in the system and can be backed in 1 MB frames.")
    smf71lox: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of fixed memory objects that are allocated in the system and can be backed in 1 MB frames.")
    smf71loa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of fixed memory objects that are allocated in the system and can be backed in 1 MB frames.")
    smf71lrm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 1 MB pages fixed in central storage.")
    smf71lrx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 1 MB pages fixed in central storage.")
    smf71lra: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 1 MB pages fixed in central storage.")
    smf71com: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of memory objects allocated in the high virtual common storage of the system.")
    smf71cox: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of memory objects allocated in the high virtual common storage of the system.")
    smf71coa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of memory objects allocated in the high virtual common storage of the system.")
    smf71crm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71crx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71cra: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71cfm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of fixed pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71cfx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of fixed pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71cfa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of fixed pages from high virtual common storage that are backed in central storage (in units of 4 KB).")
    smf71csm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of auxiliary storage slots used for high virtual common pages that are backed on DASD.")
    smf71csx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of auxiliary storage slots used for high virtual common pages that are backed on DASD.")
    smf71csa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of auxiliary storage slots used for high virtual common pages that are backed on DASD.")
    smf71som: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of memory objects allocated in the high virtual shared storage of the system.")
    smf71sox: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of memory objects allocated in the high virtual shared storage of the system.")
    smf71soa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of memory objects allocated in the high virtual shared storage of the system.")
    smf71srm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of pages from high virtual shared storage that are backed in central storage (in units of 4 KB).")
    smf71srx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of pages from high virtual shared storage that are backed in central storage (in units of 4 KB).")
    smf71sra: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of pages from high virtual shared storage that are backed in central storage (in units of 4 KB).")
    smf71grn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of GETMAIN requests that have been issued.")
    smf71fbn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of pages backed during GETMAIN requests that have been issued.")
    smf71frn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of fix requests that have been issued for storage (address spaces only) below 2 GB.")
    smf71ffn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of pages that were requested to be fixed for storage (address spaces only) below 2 GB.")
    smf711rn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger, doc="Number of first reference faults taken.")
    smf71nrn: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Number of non-first reference faults taken.")
    smf71rfl: so.Mapped[Optional[int]] = so.mapped_column(sa.Integer,
                                                          doc="Flags: Bit Meaning when set 0 SCM support enabled 1 Pageable large pages support enabled 2 Dedicated memory usage counts are invalid. 3-31")
    smf71lfa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="The maximum number of fixed 1 MB pages that can be allocated as specified in the LFAREA parameter.")
    smf71l1m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Lowest maximum number of 1 MB frames that can be used by fixed 1 MB pages.")
    smf71l1x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Highest maximum number of 1 MB frames that can be used by fixed 1 MB pages.")
    smf71l1a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average maximum number of 1 MB frames that can be used by fixed 1 MB pages.")
    smf71l2m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Reserved. Value is now in SMF71L7M.")
    smf71l2x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Reserved. Value is now in SMF71L7X.")
    smf71l2a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Reserved. Value is now in SMF71L7A.")
    smf71l3m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 1 MB frames that are in-use and are no longer available for fixed 1 MB pages.")
    smf71l3x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 1 MB frames that are in-use and are no longer available for fixed 1 MB pages.")
    smf71l3a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 1 MB frames that are in-use and are no longer available for fixed 1 MB pages.")
    smf71l7m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of available 1 MB frames that can be used by fixed 1 MB pages. Same as SMF71L2M.")
    smf71l7x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of available 1 MB frames that can be used by fixed 1 MB pages. Same as SMF71L2X.")
    smf71l7a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of available 1 MB frames that can be used by fixed 1 MB pages. Same as SMF71L2A.")
    smf71s1m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum total number of high virtual shared memory pages (in units of 4 KB).")
    smf71s1x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum total number of high virtual shared memory pages (in units of 4 KB).")
    smf71s1a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of high virtual shared memory pages (in units of 4 KB).")
    smf71s2m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of shared memory objects that are allocated in the system and can be backed in 1 MB frames")
    smf71s2x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared memory objects that are allocated in the system and can be backed in 1 MB frames")
    smf71s2a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared memory objects that are allocated in the system and can be backed in 1 MB frames")
    smf71s3m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of frames in use for shared high virtual 4K pages")
    smf71s3x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of frames in use for shared high virtual 4K pages")
    smf71s3a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of frames in use for shared high virtual 4K pages")
    smf71s4m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 1 MB pages used for shared memory objects backed in central storage.")
    smf71s4x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 1 MB pages used for shared memory objects backed in central storage.")
    smf71s4a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 1 MB pages used for shared memory objects backed in central storage.")
    smf71s5m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of auxiliary storage slots used for high virtual shared memory pages backed on DASD.")
    smf71s5x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of auxiliary storage slots used for high virtual shared memory pages backed on DASD.")
    smf71s5a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of auxiliary storage slots used for high virtual shared memory pages backed on DASD.")
    smf71s6m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high virtual shared memory pages backed on SCM storage.")
    smf71s6x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high virtual shared memory pages backed on SCM storage.")
    smf71s6a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high virtual shared memory pages backed on SCM storage.")
    smf71c1m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum total number of high virtual common memory pages (in units of 4 KB).")
    smf71c1x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum total number of high virtual common memory pages (in units of 4 KB).")
    smf71c1a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of high virtual common memory pages (in units of 4 KB).")
    smf71c2m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high virtual common memory 1 MB fixed pages")
    smf71c2x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high virtual common memory 1 MB fixed pages")
    smf71c2a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high virtual common memory 1 MB fixed pages")
    smf71c3m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high virtual common memory 1 MB pages backed in central storage")
    smf71c3x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high virtual common memory 1 MB pages backed in central storage")
    smf71c3a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high virtual common memory 1 MB pages backed in central storage")
    smf71c4m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high virtual common memory pages backed on SCM storage")
    smf71c4x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high virtual common memory pages backed on SCM storage.")
    smf71c4a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high virtual common memory pages backed on SCM storage.")
    smf71tsm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum total number of 4K SCM blocks available to ASM.")
    smf71tsx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum total number of 4K SCM blocks available to ASM.")
    smf71tsa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of 4K SCM blocks available to ASM.")
    smf71asm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of available (not in-use) SCM blocks.")
    smf71asx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of available (not in-use) SCM blocks.")
    smf71asv: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of available (not in-use) SCM blocks.")
    smf71bsm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Minimum number of bad SCM blocks.")
    smf71bsx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Maximum number of bad SCM blocks.")
    smf71bsa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Average number of bad SCM blocks.")
    smf71usm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Minimum number of SCM blocks in-use.")
    smf71usx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Maximum number of SCM blocks in-use.")
    smf71usa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Average number of SCM blocks in-use.")
    smf71tls: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger, doc="Total number of logical swaps.")
    smf71s7m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float, doc="Minimum number of shared pages backed")
    smf71s7x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of shared pages backed on SCM storage.")
    smf71s7a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of shared pages backed on SCM storage.")
    smf71lvf: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of unused central storage page frames. Same as SMF71AVF, but long floating point format.")
    smf71lvs: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of pageable address space central storage frames in the private address space. Same as SMF71AVS, but long floating point format.")
    smf71lvt: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of central storage frames used. Same as SMF71AVT, but long floating point format.")
    smf71lvr: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of non-LSQA fixed central storage frames in the private address space. Same as SMF71AVR, but long floating point format.")
    smf71lvx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of fixed central storage frames used. Same as SMF71AVX, but long floating point format.")
    smf71lvu: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of usable local page data set slots that have not been allocated. Same as SMF71AVU, but long floating point format.")
    smf71lvv: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of local page data set slots allocated to VIO private area pages. Same as SMF71AVV, but long floating point format.")
    smf71lvm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of local page data set slots allocated to non-VIO private area pages. Same as SMF71AVM, but long floating point format.")
    smf71lvb: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of unusable local page data set slots. Same as SMF71AVB, but long floating point format.")
    smf71mcf: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                          doc="Multithreading maximum capacity numerator for general purpose processors. Divide this value by 1024 to get the multithreading maximum capacity factor for all general purpose processors that were configured ONLINE for the complete interval.")
    smf71cpm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of high virtual common pages in-use")
    smf71cpx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of high virtual common pages in-use")
    smf71cpa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of high virtual common pages in-use")
    smf71plm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 1 MB frames that are in-use by pageable 1 MB pages.")
    smf71plx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 1 MB frames that are in-use by pageable 1 MB pages.")
    smf71pla: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 1 MB frames that are in-use by pageable 1 MB pages.")
    smf71gom: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of fixed 2 GB memory objects allocated in the system")
    smf71gox: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of fixed 2 GB memory objects allocated in the system")
    smf71goa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of fixed 2 GB memory objects allocated in the system")
    smf71grm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 2 GB pages fixed in central storage (same as SMF71GUM)")
    smf71grx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 2 GB pages fixed in central storage (same as SMF71GUX)")
    smf71gra: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 2 GB pages fixed in central storage (same as SMF71GUA)")
    smf71gum: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 2 GB frames in the Large Frame Area that are in-use by fixed memory objects (same as SMF71GRM)")
    smf71gux: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 2 GB frames in the Large Frame Area that are in-use by fixed memory objects (same as SMF71GRX)")
    smf71gua: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 2 GB frames in the Large Frame Area that are in-use by fixed memory objects (same as SMF71GRA)")
    smf71guh: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="High water mark for the number of 2 GB frames that are used by the system")
    smf71gam: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 2 GB frames in the Large Frame Area that are not in-use")
    smf71gax: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 2 GB frames in the Large Frame Area that are not in-use")
    smf71gaa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 2 GB frames in the Large Frame Area that are not in-use")
    smf71gfm: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Lowest maximum number of 2 GB frames that can be used by fixed 2 GB pages.")
    smf71gfx: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Highest maximum number of 2 GB frames that can be used by fixed 2 GB pages.")
    smf71gfa: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average maximum number of 2 GB frames that can be used by fixed 2 GB pages.")
    smf71nnf: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of non-nucleus frames comprising permanent storage.")
    smf71lsi: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of system-initiated demotions from pageable large frame groups to 4K page frames.")
    smf71lri: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of request-initiated demotions from pageable large frame groups to 4K page frames.")
    smf71mhw: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="High water mark of the number of 1 MB frames that were used to satisfy fixed 1 MB page requests.")
    smf71pis: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of page-ins of 4 KB pages from SCM.")
    smf71pos: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of page-outs of 4 KB pages to SCM.")
    smf71pi1: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of page-ins of 1 MB pages from SCM.")
    smf71po1: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of page-outs of 1 MB pages to SCM.")
    smf71l8m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum total number of 1 MB frames in central storage.")
    smf71l8x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum total number of 1 MB frames in central storage.")
    smf71l8a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average total number of 1 MB frames in central storage.")
    smf71l9m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of available 1 MB frames in central storage.")
    smf71l9x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of available 1 MB frames in central storage.")
    smf71l9a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of available 1 MB frames in central storage.")
    smf71l10m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                             doc="Minimum number of 1 MB frames that are in-use by memory objects.")
    smf71l10x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                             doc="Maximum number of 1 MB frames that are in-use by memory objects.")
    smf71l10a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                             doc="Average number of 1 MB frames that are in-use by memory objects.")
    smf71m6c: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of frames backing 64-bit shared page groups.")
    smf71x6c: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of frames backing 64-bit shared page groups.")
    smf71a6c: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of frames backing 64-bit shared page groups.")
    smf71m6f: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of fixed frames backing 64-bit shared page groups.")
    smf71x6f: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of fixed frames backing 64-bit shared page groups.")
    smf71a6f: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of fixed frames backing 64- bit shared page groups.")
    smf71m6b: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 24-bit frames backing 64-bit shared page groups.")
    smf71x6b: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 24-bit frames backing 64-bit shared page groups.")
    smf71a6b: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 24-bit frames backing 64-bit shared page groups.")
    smf71m6a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of auxiliary DASD slots used to back 64-bit shared page groups.")
    smf71x6a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of auxiliary DASD slots used to back 64-bit shared page groups.")
    smf71a6a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of auxiliary DASD slots used to back 64-bit shared page groups.")
    smf71m6s: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of SCM blocks used to back 64-bit shared page groups.")
    smf71x6s: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of SCM blocks used to back 64-bit shared page groups.")
    smf71a6s: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of SCM blocks used to back 64-bit shared page groups.")
    smf71m6t: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Minimum number of 64-bit shared page groups in the system.")
    smf71x6t: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Maximum number of 64-bit shared page groups in the system.")
    smf71a6t: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                            doc="Average number of 64-bit shared page groups in the system.")
    smf71_dmemassignable2g: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                          doc="Total amount of dedicated memory at system initialization that can be used by address spaces, in 2G units. Note : This field does not include dedicated")
    smf71_dmemnumberofjobsusingdmem_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                     doc="Minimum number of address spaces using dedicated memory.")
    smf71_dmemnumberofjobsusingdmem_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                     doc="Maximum number of address spaces using dedicated memory.")
    smf71_dmemnumberofjobsusingdmem_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                     doc="Average number of address spaces using dedicated memory.")
    smf71_dmemtotal2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                       doc="Minimum amount of online and offline dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemtotal2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                       doc="Maximum amount of online and offline dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemtotal2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                       doc="Average amount of online and offline dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemtotalonline2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                             doc="Minimum amount of online dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemtotalonline2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                             doc="Maximum amount of online dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemtotalonline2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                             doc="Average amount of online dedicated memory in 2G units, including dedicated memory used by the system.")
    smf71_dmemavailable2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Minimum amount of available dedicated memory in 2G units that can be used by address spaces.")
    smf71_dmemavailable2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Maximum amount of available dedicated memory in 2G units that can be used by address spaces.")
    smf71_dmemavailable2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Average amount of available dedicated memory in 2G units that can be used by address spaces.")
    smf71_dmemrequested2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Minimum amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemrequested2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Maximum amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemrequested2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                           doc="Average amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemminrequested2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Lowest minimum amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemminrequested2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Highest minimum amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemminrequested2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Average minimum amount of requested dedicated memory in 2G units over all address spaces.")
    smf71_dmemassigned2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                          doc="Minimum amount of assigned dedicated memory over all address spaces.")
    smf71_dmemassigned2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                          doc="Maximum amount of assigned dedicated memory over all address spaces.")
    smf71_dmemassigned2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                          doc="Average amount of assigned dedicated memory over all address spaces.")
    smf71_dmeminuseas2g_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Minimum amount of dedicated memory used as 2G frames over all address spaces.")
    smf71_dmeminuseas2g_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Maximum amount of dedicated memory used as 2G frames over all address spaces.")
    smf71_dmeminuseas2g_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Average amount of dedicated memory used as 2G frames over all address spaces.")
    smf71_dmeminuseas1mfixed_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Minimum amount of dedicated memory used as 1M fixed frames over all address spaces.")
    smf71_dmeminuseas1mfixed_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Maximum amount of dedicated memory used as 1M fixed frames over all address spaces.")
    smf71_dmeminuseas1mfixed_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                              doc="Average amount of dedicated memory used as 1M fixed frames over all address spaces")
    smf71_dmeminuseas1mpageable_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                 doc="Minimum amount of dedicated memory used as 1M pageable frames over all address spaces.")
    smf71_dmeminuseas1mpageable_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                 doc="Maximum amount of dedicated memory used as 1M pageable frames over all address spaces.")
    smf71_dmeminuseas1mpageable_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                 doc="Average amount of dedicated memory used as 1M pageable frames over all address spaces.")
    smf71_dmeminuseas4k_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Minimum amount of dedicated memory used as 4K frames over all address spaces.")
    smf71_dmeminuseas4k_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Maximum amount of dedicated memory used as 4K frames over all address spaces.")
    smf71_dmeminuseas4k_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="Average amount of dedicated memory used as 4K frames over all address spaces.")
    smf71_dmeminuseasdattables4k_m: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                  doc="Minimum number of dedicated memory frames in 4K units backing DAT tables (system use).")
    smf71_dmeminuseasdattables4k_x: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                  doc="Maximum number of dedicated memory frames in 4K units backing DAT tables (system use).")
    smf71_dmeminuseasdattables4k_a: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                                  doc="Average number of dedicated memory frames in 4K units backing DAT tables (system use).")
    total_nvio_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                           doc="Total non-VIO page in non swap block (smf71blk + smf71sbi).")
    pg_mv_within_cs: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                 doc="The rate of page movement within central storage.")
    pg_mv_rate: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                              doc="The rate of page movement. This includes each page movement from one frame to another frame independent of the location of the frame.")
    pg_mv_time_percentage: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                         doc="The percentage of general purpose processor time, including normalized AAP, CBP and IIP times, spent on page movement to obtain or free a particular type of frame for a page to be fixed (that is, a frame below the 16 megabyte line in central processor storage). The calculation is the amount of processor time needed to steal the page (including the time to move the contents of the frames, but not the time to move the new contents into the frames) divided by the length of the interval.")
    sys_sum_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                     doc="The sum of system pageable areas non swap paged-out.")
    avg_pg_per_blk: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                  doc="The average size of address space non-VIO blocks that were paged-in during the interval. It does not include swap or hiperspace pages.")
    blk_per_seconds: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                   doc="The rate of page faults for pages that were part of a block.")
    pg_fault_rate: so.Mapped[Optional[float]] = so.mapped_column(sa.Float,
                                                                 doc="The rate of page faults for all pages in events per second, excluding VIO and Hiperspace. The rate includes pages read from DASD only, not from expanded storage.")
    sys_csa_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                        doc="CSA of system pageable areas non swap blocked paged-in.")
    sys_csa_pgin_nswap_nblk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                         doc="CSA of system pageable areas non swap non blocked paged-in.")
    as_nvio_pgin_nswap_nblk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                         doc="Individual address space non-VIO non swap non block paged-in.")
    total_nvio_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                        doc="The total non-VIO non swap paged-out.")
    as_sum_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                    doc="Sum of address space non swap paged-out")
    total_vio_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                       doc="The total VIO non swap paged-out.")
    as_sum_pgin_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                  doc="Sum of address space swap paged-in")
    as_sum_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                       doc="Sum of address space non swap paged-in block")
    as_sum_pgin_nswap_nblk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                        doc="Sum of address space non swap non block paged-in")
    as_sum_pgout_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                   doc="Sum of address space swap paged-out")
    total_hspace_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                             doc="The sum of system pageable areas and address space hiperspace non swap blocked paged-in.")
    total_hspace_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                          doc="The sum of system pageable areas and address space hiperspace non swap blocked paged-out.")
    total_vio_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                          doc="The total VIO non swap blocked paged-in.")
    total_nvio_pgin_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                      doc="The total non-VIO swap paged-in.")
    total_nvio_pgout_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                       doc="The total non-VIO swap paged-out.")
    total_sum_pgin_nswap_blk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                          doc="Sum of system pageable areas sum and address sum of non swap blocked paged-in.")
    total_sum_pgin_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                     doc="Sum of system pageable areas sum and address sum of swap paged-in.")
    total_sum_pgin_nswap_nblk: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                           doc="Sum of system pageable areas sum and address sum of non swap non blocked paged-in.")
    total_sum_pgout_swap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                      doc="Sum of system pageable areas sum and address sum of swap paged-out.")
    total_sum_pgout_nswap: so.Mapped[Optional[int]] = so.mapped_column(sa.BigInteger,
                                                                       doc="Sum of system pageable areas sum and address sum of non swap paged-out.")
